/*
 * PricingService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.1.4089
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ItemPriceDto
 */
public class ItemPriceDtoTest {
    private final ItemPriceDto model = new ItemPriceDto();

    /**
     * Model tests for ItemPriceDto
     */
    @Test
    public void testItemPriceDto() {
        // TODO: test ItemPriceDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'itemId'
     */
    @Test
    public void itemIdTest() {
        // TODO: test itemId
    }

    /**
     * Test the property 'unitId'
     */
    @Test
    public void unitIdTest() {
        // TODO: test unitId
    }

    /**
     * Test the property 'currencyId'
     */
    @Test
    public void currencyIdTest() {
        // TODO: test currencyId
    }

    /**
     * Test the property 'discountId'
     */
    @Test
    public void discountIdTest() {
        // TODO: test discountId
    }

    /**
     * Test the property 'unitGroupId'
     */
    @Test
    public void unitGroupIdTest() {
        // TODO: test unitGroupId
    }

    /**
     * Test the property 'priceListId'
     */
    @Test
    public void priceListIdTest() {
        // TODO: test priceListId
    }

    /**
     * Test the property 'discountListId'
     */
    @Test
    public void discountListIdTest() {
        // TODO: test discountListId
    }

    /**
     * Test the property 'roundingPolicyId'
     */
    @Test
    public void roundingPolicyIdTest() {
        // TODO: test roundingPolicyId
    }

    /**
     * Test the property 'enrollmentId'
     */
    @Test
    public void enrollmentIdTest() {
        // TODO: test enrollmentId
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'percent'
     */
    @Test
    public void percentTest() {
        // TODO: test percent
    }

}
