/*
 * PricingService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorEnvelope;
import org.openapitools.client.model.ItemPriceCalculationEnvelope;
import org.openapitools.client.model.MoneyEnvelope;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PricesApi
 */
@Disabled
public class PricesApiTest {

    private final PricesApi api = new PricesApi();

    /**
     * Gets the final price for an item
     *
     * Gets the final price for an item after all discounts and taxes in the specified currency.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFinalPriceTest() throws ApiException {
        UUID itemId = null;
        String currencyId = null;
        String apiVersion = null;
        String xApiVersion = null;
        MoneyEnvelope response = api.getFinalPrice(itemId, currencyId, apiVersion, xApiVersion);
        // TODO: test validations
    }

    /**
     * Gets the calculated price for an item
     *
     * Calculates the price for an item considering price list, discount list, quantity, and currency.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPriceTest() throws ApiException {
        UUID itemId = null;
        UUID priceListId = null;
        UUID discountsListId = null;
        Double quantity = null;
        String currencyId = null;
        String apiVersion = null;
        String xApiVersion = null;
        ItemPriceCalculationEnvelope response = api.getPrice(itemId, priceListId, discountsListId, quantity, currencyId, apiVersion, xApiVersion);
        // TODO: test validations
    }

    /**
     * Gets total savings for an item
     *
     * Gets the total savings amount for an item in the specified currency.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTotalSavingsInUsdTest() throws ApiException {
        UUID itemId = null;
        String currencyId = null;
        String apiVersion = null;
        String xApiVersion = null;
        MoneyEnvelope response = api.getTotalSavingsInUsd(itemId, currencyId, apiVersion, xApiVersion);
        // TODO: test validations
    }

    /**
     * Gets total taxes for an item
     *
     * Gets the total tax amount for an item in the specified currency.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTotalTaxesInUsdTest() throws ApiException {
        UUID itemId = null;
        String currencyId = null;
        String apiVersion = null;
        String xApiVersion = null;
        MoneyEnvelope response = api.getTotalTaxesInUsd(itemId, currencyId, apiVersion, xApiVersion);
        // TODO: test validations
    }

}
