/*
 * ContentService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5401
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.Assembly;
import org.openapitools.client.model.ConstructorInfo;
import org.openapitools.client.model.CustomAttributeData;
import org.openapitools.client.model.EventInfo;
import org.openapitools.client.model.FieldInfo;
import org.openapitools.client.model.MemberInfo;
import org.openapitools.client.model.MethodBase;
import org.openapitools.client.model.MethodInfo;
import org.openapitools.client.model.Module;
import org.openapitools.client.model.PropertyInfo;
import org.openapitools.client.model.RuntimeTypeHandle;
import org.openapitools.client.model.StructLayoutAttribute;
import org.openapitools.client.model.Type;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TypeInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-30T19:47:31.019772200-05:00[America/Bogota]", comments = "Generator version: 7.9.0")
public class TypeInfo {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CUSTOM_ATTRIBUTES = "customAttributes";
  @SerializedName(SERIALIZED_NAME_CUSTOM_ATTRIBUTES)
  private List<CustomAttributeData> customAttributes;

  public static final String SERIALIZED_NAME_IS_COLLECTIBLE = "isCollectible";
  @SerializedName(SERIALIZED_NAME_IS_COLLECTIBLE)
  private Boolean isCollectible;

  public static final String SERIALIZED_NAME_METADATA_TOKEN = "metadataToken";
  @SerializedName(SERIALIZED_NAME_METADATA_TOKEN)
  private Integer metadataToken;

  /**
   * Gets or Sets memberType
   */
  @JsonAdapter(MemberTypeEnum.Adapter.class)
  public enum MemberTypeEnum {
    CONSTRUCTOR("Constructor"),
    
    EVENT("Event"),
    
    FIELD("Field"),
    
    METHOD("Method"),
    
    PROPERTY("Property"),
    
    TYPE_INFO("TypeInfo"),
    
    CUSTOM("Custom"),
    
    NESTED_TYPE("NestedType"),
    
    ALL("All");

    private String value;

    MemberTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MemberTypeEnum fromValue(String value) {
      for (MemberTypeEnum b : MemberTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<MemberTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MemberTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MemberTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return MemberTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      MemberTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_MEMBER_TYPE = "memberType";
  @SerializedName(SERIALIZED_NAME_MEMBER_TYPE)
  private MemberTypeEnum memberType;

  public static final String SERIALIZED_NAME_NAMESPACE = "namespace";
  @SerializedName(SERIALIZED_NAME_NAMESPACE)
  private String namespace;

  public static final String SERIALIZED_NAME_ASSEMBLY_QUALIFIED_NAME = "assemblyQualifiedName";
  @SerializedName(SERIALIZED_NAME_ASSEMBLY_QUALIFIED_NAME)
  private String assemblyQualifiedName;

  public static final String SERIALIZED_NAME_FULL_NAME = "fullName";
  @SerializedName(SERIALIZED_NAME_FULL_NAME)
  private String fullName;

  public static final String SERIALIZED_NAME_ASSEMBLY = "assembly";
  @SerializedName(SERIALIZED_NAME_ASSEMBLY)
  private Assembly assembly;

  public static final String SERIALIZED_NAME_MODULE = "module";
  @SerializedName(SERIALIZED_NAME_MODULE)
  private Module module;

  public static final String SERIALIZED_NAME_IS_INTERFACE = "isInterface";
  @SerializedName(SERIALIZED_NAME_IS_INTERFACE)
  private Boolean isInterface;

  public static final String SERIALIZED_NAME_IS_NESTED = "isNested";
  @SerializedName(SERIALIZED_NAME_IS_NESTED)
  private Boolean isNested;

  public static final String SERIALIZED_NAME_DECLARING_TYPE = "declaringType";
  @SerializedName(SERIALIZED_NAME_DECLARING_TYPE)
  private Type declaringType;

  public static final String SERIALIZED_NAME_DECLARING_METHOD = "declaringMethod";
  @SerializedName(SERIALIZED_NAME_DECLARING_METHOD)
  private MethodBase declaringMethod;

  public static final String SERIALIZED_NAME_REFLECTED_TYPE = "reflectedType";
  @SerializedName(SERIALIZED_NAME_REFLECTED_TYPE)
  private Type reflectedType;

  public static final String SERIALIZED_NAME_UNDERLYING_SYSTEM_TYPE = "underlyingSystemType";
  @SerializedName(SERIALIZED_NAME_UNDERLYING_SYSTEM_TYPE)
  private Type underlyingSystemType;

  public static final String SERIALIZED_NAME_IS_TYPE_DEFINITION = "isTypeDefinition";
  @SerializedName(SERIALIZED_NAME_IS_TYPE_DEFINITION)
  private Boolean isTypeDefinition;

  public static final String SERIALIZED_NAME_IS_ARRAY = "isArray";
  @SerializedName(SERIALIZED_NAME_IS_ARRAY)
  private Boolean isArray;

  public static final String SERIALIZED_NAME_IS_BY_REF = "isByRef";
  @SerializedName(SERIALIZED_NAME_IS_BY_REF)
  private Boolean isByRef;

  public static final String SERIALIZED_NAME_IS_POINTER = "isPointer";
  @SerializedName(SERIALIZED_NAME_IS_POINTER)
  private Boolean isPointer;

  public static final String SERIALIZED_NAME_IS_CONSTRUCTED_GENERIC_TYPE = "isConstructedGenericType";
  @SerializedName(SERIALIZED_NAME_IS_CONSTRUCTED_GENERIC_TYPE)
  private Boolean isConstructedGenericType;

  public static final String SERIALIZED_NAME_IS_GENERIC_PARAMETER = "isGenericParameter";
  @SerializedName(SERIALIZED_NAME_IS_GENERIC_PARAMETER)
  private Boolean isGenericParameter;

  public static final String SERIALIZED_NAME_IS_GENERIC_TYPE_PARAMETER = "isGenericTypeParameter";
  @SerializedName(SERIALIZED_NAME_IS_GENERIC_TYPE_PARAMETER)
  private Boolean isGenericTypeParameter;

  public static final String SERIALIZED_NAME_IS_GENERIC_METHOD_PARAMETER = "isGenericMethodParameter";
  @SerializedName(SERIALIZED_NAME_IS_GENERIC_METHOD_PARAMETER)
  private Boolean isGenericMethodParameter;

  public static final String SERIALIZED_NAME_IS_GENERIC_TYPE = "isGenericType";
  @SerializedName(SERIALIZED_NAME_IS_GENERIC_TYPE)
  private Boolean isGenericType;

  public static final String SERIALIZED_NAME_IS_GENERIC_TYPE_DEFINITION = "isGenericTypeDefinition";
  @SerializedName(SERIALIZED_NAME_IS_GENERIC_TYPE_DEFINITION)
  private Boolean isGenericTypeDefinition;

  public static final String SERIALIZED_NAME_IS_S_Z_ARRAY = "isSZArray";
  @SerializedName(SERIALIZED_NAME_IS_S_Z_ARRAY)
  private Boolean isSZArray;

  public static final String SERIALIZED_NAME_IS_VARIABLE_BOUND_ARRAY = "isVariableBoundArray";
  @SerializedName(SERIALIZED_NAME_IS_VARIABLE_BOUND_ARRAY)
  private Boolean isVariableBoundArray;

  public static final String SERIALIZED_NAME_IS_BY_REF_LIKE = "isByRefLike";
  @SerializedName(SERIALIZED_NAME_IS_BY_REF_LIKE)
  private Boolean isByRefLike;

  public static final String SERIALIZED_NAME_IS_FUNCTION_POINTER = "isFunctionPointer";
  @SerializedName(SERIALIZED_NAME_IS_FUNCTION_POINTER)
  private Boolean isFunctionPointer;

  public static final String SERIALIZED_NAME_IS_UNMANAGED_FUNCTION_POINTER = "isUnmanagedFunctionPointer";
  @SerializedName(SERIALIZED_NAME_IS_UNMANAGED_FUNCTION_POINTER)
  private Boolean isUnmanagedFunctionPointer;

  public static final String SERIALIZED_NAME_HAS_ELEMENT_TYPE = "hasElementType";
  @SerializedName(SERIALIZED_NAME_HAS_ELEMENT_TYPE)
  private Boolean hasElementType;

  public static final String SERIALIZED_NAME_GENERIC_TYPE_ARGUMENTS = "genericTypeArguments";
  @SerializedName(SERIALIZED_NAME_GENERIC_TYPE_ARGUMENTS)
  private List<Type> genericTypeArguments;

  public static final String SERIALIZED_NAME_GENERIC_PARAMETER_POSITION = "genericParameterPosition";
  @SerializedName(SERIALIZED_NAME_GENERIC_PARAMETER_POSITION)
  private Integer genericParameterPosition;

  /**
   * Gets or Sets genericParameterAttributes
   */
  @JsonAdapter(GenericParameterAttributesEnum.Adapter.class)
  public enum GenericParameterAttributesEnum {
    NONE("None"),
    
    COVARIANT("Covariant"),
    
    CONTRAVARIANT("Contravariant"),
    
    VARIANCE_MASK("VarianceMask"),
    
    REFERENCE_TYPE_CONSTRAINT("ReferenceTypeConstraint"),
    
    NOT_NULLABLE_VALUE_TYPE_CONSTRAINT("NotNullableValueTypeConstraint"),
    
    DEFAULT_CONSTRUCTOR_CONSTRAINT("DefaultConstructorConstraint"),
    
    SPECIAL_CONSTRAINT_MASK("SpecialConstraintMask"),
    
    ALLOW_BY_REF_LIKE("AllowByRefLike");

    private String value;

    GenericParameterAttributesEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static GenericParameterAttributesEnum fromValue(String value) {
      for (GenericParameterAttributesEnum b : GenericParameterAttributesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<GenericParameterAttributesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final GenericParameterAttributesEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public GenericParameterAttributesEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return GenericParameterAttributesEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      GenericParameterAttributesEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_GENERIC_PARAMETER_ATTRIBUTES = "genericParameterAttributes";
  @SerializedName(SERIALIZED_NAME_GENERIC_PARAMETER_ATTRIBUTES)
  private GenericParameterAttributesEnum genericParameterAttributes;

  /**
   * Gets or Sets attributes
   */
  @JsonAdapter(AttributesEnum.Adapter.class)
  public enum AttributesEnum {
    NOT_PUBLIC("NotPublic"),
    
    PUBLIC("Public"),
    
    NESTED_PUBLIC("NestedPublic"),
    
    NESTED_PRIVATE("NestedPrivate"),
    
    NESTED_FAMILY("NestedFamily"),
    
    NESTED_ASSEMBLY("NestedAssembly"),
    
    NESTED_FAM_AND_ASSEM("NestedFamANDAssem"),
    
    VISIBILITY_MASK("VisibilityMask"),
    
    SEQUENTIAL_LAYOUT("SequentialLayout"),
    
    EXPLICIT_LAYOUT("ExplicitLayout"),
    
    LAYOUT_MASK("LayoutMask"),
    
    INTERFACE("Interface"),
    
    ABSTRACT("Abstract"),
    
    SEALED("Sealed"),
    
    SPECIAL_NAME("SpecialName"),
    
    RT_SPECIAL_NAME("RTSpecialName"),
    
    IMPORT("Import"),
    
    SERIALIZABLE("Serializable"),
    
    WINDOWS_RUNTIME("WindowsRuntime"),
    
    UNICODE_CLASS("UnicodeClass"),
    
    AUTO_CLASS("AutoClass"),
    
    STRING_FORMAT_MASK("StringFormatMask"),
    
    HAS_SECURITY("HasSecurity"),
    
    RESERVED_MASK("ReservedMask"),
    
    BEFORE_FIELD_INIT("BeforeFieldInit"),
    
    CUSTOM_FORMAT_MASK("CustomFormatMask");

    private String value;

    AttributesEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AttributesEnum fromValue(String value) {
      for (AttributesEnum b : AttributesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AttributesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AttributesEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AttributesEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AttributesEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      AttributesEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private AttributesEnum attributes;

  public static final String SERIALIZED_NAME_IS_ABSTRACT = "isAbstract";
  @SerializedName(SERIALIZED_NAME_IS_ABSTRACT)
  private Boolean isAbstract;

  public static final String SERIALIZED_NAME_IS_IMPORT = "isImport";
  @SerializedName(SERIALIZED_NAME_IS_IMPORT)
  private Boolean isImport;

  public static final String SERIALIZED_NAME_IS_SEALED = "isSealed";
  @SerializedName(SERIALIZED_NAME_IS_SEALED)
  private Boolean isSealed;

  public static final String SERIALIZED_NAME_IS_SPECIAL_NAME = "isSpecialName";
  @SerializedName(SERIALIZED_NAME_IS_SPECIAL_NAME)
  private Boolean isSpecialName;

  public static final String SERIALIZED_NAME_IS_CLASS = "isClass";
  @SerializedName(SERIALIZED_NAME_IS_CLASS)
  private Boolean isClass;

  public static final String SERIALIZED_NAME_IS_NESTED_ASSEMBLY = "isNestedAssembly";
  @SerializedName(SERIALIZED_NAME_IS_NESTED_ASSEMBLY)
  private Boolean isNestedAssembly;

  public static final String SERIALIZED_NAME_IS_NESTED_FAM_A_N_D_ASSEM = "isNestedFamANDAssem";
  @SerializedName(SERIALIZED_NAME_IS_NESTED_FAM_A_N_D_ASSEM)
  private Boolean isNestedFamANDAssem;

  public static final String SERIALIZED_NAME_IS_NESTED_FAMILY = "isNestedFamily";
  @SerializedName(SERIALIZED_NAME_IS_NESTED_FAMILY)
  private Boolean isNestedFamily;

  public static final String SERIALIZED_NAME_IS_NESTED_FAM_O_R_ASSEM = "isNestedFamORAssem";
  @SerializedName(SERIALIZED_NAME_IS_NESTED_FAM_O_R_ASSEM)
  private Boolean isNestedFamORAssem;

  public static final String SERIALIZED_NAME_IS_NESTED_PRIVATE = "isNestedPrivate";
  @SerializedName(SERIALIZED_NAME_IS_NESTED_PRIVATE)
  private Boolean isNestedPrivate;

  public static final String SERIALIZED_NAME_IS_NESTED_PUBLIC = "isNestedPublic";
  @SerializedName(SERIALIZED_NAME_IS_NESTED_PUBLIC)
  private Boolean isNestedPublic;

  public static final String SERIALIZED_NAME_IS_NOT_PUBLIC = "isNotPublic";
  @SerializedName(SERIALIZED_NAME_IS_NOT_PUBLIC)
  private Boolean isNotPublic;

  public static final String SERIALIZED_NAME_IS_PUBLIC = "isPublic";
  @SerializedName(SERIALIZED_NAME_IS_PUBLIC)
  private Boolean isPublic;

  public static final String SERIALIZED_NAME_IS_AUTO_LAYOUT = "isAutoLayout";
  @SerializedName(SERIALIZED_NAME_IS_AUTO_LAYOUT)
  private Boolean isAutoLayout;

  public static final String SERIALIZED_NAME_IS_EXPLICIT_LAYOUT = "isExplicitLayout";
  @SerializedName(SERIALIZED_NAME_IS_EXPLICIT_LAYOUT)
  private Boolean isExplicitLayout;

  public static final String SERIALIZED_NAME_IS_LAYOUT_SEQUENTIAL = "isLayoutSequential";
  @SerializedName(SERIALIZED_NAME_IS_LAYOUT_SEQUENTIAL)
  private Boolean isLayoutSequential;

  public static final String SERIALIZED_NAME_IS_ANSI_CLASS = "isAnsiClass";
  @SerializedName(SERIALIZED_NAME_IS_ANSI_CLASS)
  private Boolean isAnsiClass;

  public static final String SERIALIZED_NAME_IS_AUTO_CLASS = "isAutoClass";
  @SerializedName(SERIALIZED_NAME_IS_AUTO_CLASS)
  private Boolean isAutoClass;

  public static final String SERIALIZED_NAME_IS_UNICODE_CLASS = "isUnicodeClass";
  @SerializedName(SERIALIZED_NAME_IS_UNICODE_CLASS)
  private Boolean isUnicodeClass;

  public static final String SERIALIZED_NAME_IS_C_O_M_OBJECT = "isCOMObject";
  @SerializedName(SERIALIZED_NAME_IS_C_O_M_OBJECT)
  private Boolean isCOMObject;

  public static final String SERIALIZED_NAME_IS_CONTEXTFUL = "isContextful";
  @SerializedName(SERIALIZED_NAME_IS_CONTEXTFUL)
  private Boolean isContextful;

  public static final String SERIALIZED_NAME_IS_ENUM = "isEnum";
  @SerializedName(SERIALIZED_NAME_IS_ENUM)
  private Boolean isEnum;

  public static final String SERIALIZED_NAME_IS_MARSHAL_BY_REF = "isMarshalByRef";
  @SerializedName(SERIALIZED_NAME_IS_MARSHAL_BY_REF)
  private Boolean isMarshalByRef;

  public static final String SERIALIZED_NAME_IS_PRIMITIVE = "isPrimitive";
  @SerializedName(SERIALIZED_NAME_IS_PRIMITIVE)
  private Boolean isPrimitive;

  public static final String SERIALIZED_NAME_IS_VALUE_TYPE = "isValueType";
  @SerializedName(SERIALIZED_NAME_IS_VALUE_TYPE)
  private Boolean isValueType;

  public static final String SERIALIZED_NAME_IS_SIGNATURE_TYPE = "isSignatureType";
  @SerializedName(SERIALIZED_NAME_IS_SIGNATURE_TYPE)
  private Boolean isSignatureType;

  public static final String SERIALIZED_NAME_IS_SECURITY_CRITICAL = "isSecurityCritical";
  @SerializedName(SERIALIZED_NAME_IS_SECURITY_CRITICAL)
  private Boolean isSecurityCritical;

  public static final String SERIALIZED_NAME_IS_SECURITY_SAFE_CRITICAL = "isSecuritySafeCritical";
  @SerializedName(SERIALIZED_NAME_IS_SECURITY_SAFE_CRITICAL)
  private Boolean isSecuritySafeCritical;

  public static final String SERIALIZED_NAME_IS_SECURITY_TRANSPARENT = "isSecurityTransparent";
  @SerializedName(SERIALIZED_NAME_IS_SECURITY_TRANSPARENT)
  private Boolean isSecurityTransparent;

  public static final String SERIALIZED_NAME_STRUCT_LAYOUT_ATTRIBUTE = "structLayoutAttribute";
  @SerializedName(SERIALIZED_NAME_STRUCT_LAYOUT_ATTRIBUTE)
  private StructLayoutAttribute structLayoutAttribute;

  public static final String SERIALIZED_NAME_TYPE_INITIALIZER = "typeInitializer";
  @SerializedName(SERIALIZED_NAME_TYPE_INITIALIZER)
  private ConstructorInfo typeInitializer;

  public static final String SERIALIZED_NAME_TYPE_HANDLE = "typeHandle";
  @SerializedName(SERIALIZED_NAME_TYPE_HANDLE)
  private RuntimeTypeHandle typeHandle;

  public static final String SERIALIZED_NAME_GUID = "guid";
  @SerializedName(SERIALIZED_NAME_GUID)
  private UUID guid;

  public static final String SERIALIZED_NAME_BASE_TYPE = "baseType";
  @SerializedName(SERIALIZED_NAME_BASE_TYPE)
  private Type baseType;

  public static final String SERIALIZED_NAME_IS_SERIALIZABLE = "isSerializable";
  @Deprecated
  @SerializedName(SERIALIZED_NAME_IS_SERIALIZABLE)
  private Boolean isSerializable;

  public static final String SERIALIZED_NAME_CONTAINS_GENERIC_PARAMETERS = "containsGenericParameters";
  @SerializedName(SERIALIZED_NAME_CONTAINS_GENERIC_PARAMETERS)
  private Boolean containsGenericParameters;

  public static final String SERIALIZED_NAME_IS_VISIBLE = "isVisible";
  @SerializedName(SERIALIZED_NAME_IS_VISIBLE)
  private Boolean isVisible;

  public static final String SERIALIZED_NAME_GENERIC_TYPE_PARAMETERS = "genericTypeParameters";
  @SerializedName(SERIALIZED_NAME_GENERIC_TYPE_PARAMETERS)
  private List<Type> genericTypeParameters;

  public static final String SERIALIZED_NAME_DECLARED_CONSTRUCTORS = "declaredConstructors";
  @SerializedName(SERIALIZED_NAME_DECLARED_CONSTRUCTORS)
  private List<ConstructorInfo> declaredConstructors;

  public static final String SERIALIZED_NAME_DECLARED_EVENTS = "declaredEvents";
  @SerializedName(SERIALIZED_NAME_DECLARED_EVENTS)
  private List<EventInfo> declaredEvents;

  public static final String SERIALIZED_NAME_DECLARED_FIELDS = "declaredFields";
  @SerializedName(SERIALIZED_NAME_DECLARED_FIELDS)
  private List<FieldInfo> declaredFields;

  public static final String SERIALIZED_NAME_DECLARED_MEMBERS = "declaredMembers";
  @SerializedName(SERIALIZED_NAME_DECLARED_MEMBERS)
  private List<MemberInfo> declaredMembers;

  public static final String SERIALIZED_NAME_DECLARED_METHODS = "declaredMethods";
  @SerializedName(SERIALIZED_NAME_DECLARED_METHODS)
  private List<MethodInfo> declaredMethods;

  public static final String SERIALIZED_NAME_DECLARED_NESTED_TYPES = "declaredNestedTypes";
  @SerializedName(SERIALIZED_NAME_DECLARED_NESTED_TYPES)
  private List<TypeInfo> declaredNestedTypes;

  public static final String SERIALIZED_NAME_DECLARED_PROPERTIES = "declaredProperties";
  @SerializedName(SERIALIZED_NAME_DECLARED_PROPERTIES)
  private List<PropertyInfo> declaredProperties;

  public static final String SERIALIZED_NAME_IMPLEMENTED_INTERFACES = "implementedInterfaces";
  @SerializedName(SERIALIZED_NAME_IMPLEMENTED_INTERFACES)
  private List<Type> implementedInterfaces;

  public TypeInfo() {
  }

  public TypeInfo(
     String name, 
     List<CustomAttributeData> customAttributes, 
     Boolean isCollectible, 
     Integer metadataToken, 
     MemberTypeEnum memberType, 
     String namespace, 
     String assemblyQualifiedName, 
     String fullName, 
     Boolean isInterface, 
     Boolean isNested, 
     Boolean isTypeDefinition, 
     Boolean isArray, 
     Boolean isByRef, 
     Boolean isPointer, 
     Boolean isConstructedGenericType, 
     Boolean isGenericParameter, 
     Boolean isGenericTypeParameter, 
     Boolean isGenericMethodParameter, 
     Boolean isGenericType, 
     Boolean isGenericTypeDefinition, 
     Boolean isSZArray, 
     Boolean isVariableBoundArray, 
     Boolean isByRefLike, 
     Boolean isFunctionPointer, 
     Boolean isUnmanagedFunctionPointer, 
     Boolean hasElementType, 
     List<Type> genericTypeArguments, 
     Integer genericParameterPosition, 
     GenericParameterAttributesEnum genericParameterAttributes, 
     AttributesEnum attributes, 
     Boolean isAbstract, 
     Boolean isImport, 
     Boolean isSealed, 
     Boolean isSpecialName, 
     Boolean isClass, 
     Boolean isNestedAssembly, 
     Boolean isNestedFamANDAssem, 
     Boolean isNestedFamily, 
     Boolean isNestedFamORAssem, 
     Boolean isNestedPrivate, 
     Boolean isNestedPublic, 
     Boolean isNotPublic, 
     Boolean isPublic, 
     Boolean isAutoLayout, 
     Boolean isExplicitLayout, 
     Boolean isLayoutSequential, 
     Boolean isAnsiClass, 
     Boolean isAutoClass, 
     Boolean isUnicodeClass, 
     Boolean isCOMObject, 
     Boolean isContextful, 
     Boolean isEnum, 
     Boolean isMarshalByRef, 
     Boolean isPrimitive, 
     Boolean isValueType, 
     Boolean isSignatureType, 
     Boolean isSecurityCritical, 
     Boolean isSecuritySafeCritical, 
     Boolean isSecurityTransparent, 
     UUID guid, 
     Boolean isSerializable, 
     Boolean containsGenericParameters, 
     Boolean isVisible, 
     List<Type> genericTypeParameters, 
     List<ConstructorInfo> declaredConstructors, 
     List<EventInfo> declaredEvents, 
     List<FieldInfo> declaredFields, 
     List<MemberInfo> declaredMembers, 
     List<MethodInfo> declaredMethods, 
     List<TypeInfo> declaredNestedTypes, 
     List<PropertyInfo> declaredProperties, 
     List<Type> implementedInterfaces
  ) {
    this();
    this.name = name;
    this.customAttributes = customAttributes;
    this.isCollectible = isCollectible;
    this.metadataToken = metadataToken;
    this.memberType = memberType;
    this.namespace = namespace;
    this.assemblyQualifiedName = assemblyQualifiedName;
    this.fullName = fullName;
    this.isInterface = isInterface;
    this.isNested = isNested;
    this.isTypeDefinition = isTypeDefinition;
    this.isArray = isArray;
    this.isByRef = isByRef;
    this.isPointer = isPointer;
    this.isConstructedGenericType = isConstructedGenericType;
    this.isGenericParameter = isGenericParameter;
    this.isGenericTypeParameter = isGenericTypeParameter;
    this.isGenericMethodParameter = isGenericMethodParameter;
    this.isGenericType = isGenericType;
    this.isGenericTypeDefinition = isGenericTypeDefinition;
    this.isSZArray = isSZArray;
    this.isVariableBoundArray = isVariableBoundArray;
    this.isByRefLike = isByRefLike;
    this.isFunctionPointer = isFunctionPointer;
    this.isUnmanagedFunctionPointer = isUnmanagedFunctionPointer;
    this.hasElementType = hasElementType;
    this.genericTypeArguments = genericTypeArguments;
    this.genericParameterPosition = genericParameterPosition;
    this.genericParameterAttributes = genericParameterAttributes;
    this.attributes = attributes;
    this.isAbstract = isAbstract;
    this.isImport = isImport;
    this.isSealed = isSealed;
    this.isSpecialName = isSpecialName;
    this.isClass = isClass;
    this.isNestedAssembly = isNestedAssembly;
    this.isNestedFamANDAssem = isNestedFamANDAssem;
    this.isNestedFamily = isNestedFamily;
    this.isNestedFamORAssem = isNestedFamORAssem;
    this.isNestedPrivate = isNestedPrivate;
    this.isNestedPublic = isNestedPublic;
    this.isNotPublic = isNotPublic;
    this.isPublic = isPublic;
    this.isAutoLayout = isAutoLayout;
    this.isExplicitLayout = isExplicitLayout;
    this.isLayoutSequential = isLayoutSequential;
    this.isAnsiClass = isAnsiClass;
    this.isAutoClass = isAutoClass;
    this.isUnicodeClass = isUnicodeClass;
    this.isCOMObject = isCOMObject;
    this.isContextful = isContextful;
    this.isEnum = isEnum;
    this.isMarshalByRef = isMarshalByRef;
    this.isPrimitive = isPrimitive;
    this.isValueType = isValueType;
    this.isSignatureType = isSignatureType;
    this.isSecurityCritical = isSecurityCritical;
    this.isSecuritySafeCritical = isSecuritySafeCritical;
    this.isSecurityTransparent = isSecurityTransparent;
    this.guid = guid;
    this.isSerializable = isSerializable;
    this.containsGenericParameters = containsGenericParameters;
    this.isVisible = isVisible;
    this.genericTypeParameters = genericTypeParameters;
    this.declaredConstructors = declaredConstructors;
    this.declaredEvents = declaredEvents;
    this.declaredFields = declaredFields;
    this.declaredMembers = declaredMembers;
    this.declaredMethods = declaredMethods;
    this.declaredNestedTypes = declaredNestedTypes;
    this.declaredProperties = declaredProperties;
    this.implementedInterfaces = implementedInterfaces;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }



  /**
   * Get customAttributes
   * @return customAttributes
   */
  @javax.annotation.Nullable
  public List<CustomAttributeData> getCustomAttributes() {
    return customAttributes;
  }



  /**
   * Get isCollectible
   * @return isCollectible
   */
  @javax.annotation.Nullable
  public Boolean getIsCollectible() {
    return isCollectible;
  }



  /**
   * Get metadataToken
   * @return metadataToken
   */
  @javax.annotation.Nullable
  public Integer getMetadataToken() {
    return metadataToken;
  }



  /**
   * Get memberType
   * @return memberType
   */
  @javax.annotation.Nullable
  public MemberTypeEnum getMemberType() {
    return memberType;
  }



  /**
   * Get namespace
   * @return namespace
   */
  @javax.annotation.Nullable
  public String getNamespace() {
    return namespace;
  }



  /**
   * Get assemblyQualifiedName
   * @return assemblyQualifiedName
   */
  @javax.annotation.Nullable
  public String getAssemblyQualifiedName() {
    return assemblyQualifiedName;
  }



  /**
   * Get fullName
   * @return fullName
   */
  @javax.annotation.Nullable
  public String getFullName() {
    return fullName;
  }



  public TypeInfo assembly(Assembly assembly) {
    this.assembly = assembly;
    return this;
  }

  /**
   * Get assembly
   * @return assembly
   */
  @javax.annotation.Nullable
  public Assembly getAssembly() {
    return assembly;
  }

  public void setAssembly(Assembly assembly) {
    this.assembly = assembly;
  }


  public TypeInfo module(Module module) {
    this.module = module;
    return this;
  }

  /**
   * Get module
   * @return module
   */
  @javax.annotation.Nullable
  public Module getModule() {
    return module;
  }

  public void setModule(Module module) {
    this.module = module;
  }


  /**
   * Get isInterface
   * @return isInterface
   */
  @javax.annotation.Nullable
  public Boolean getIsInterface() {
    return isInterface;
  }



  /**
   * Get isNested
   * @return isNested
   */
  @javax.annotation.Nullable
  public Boolean getIsNested() {
    return isNested;
  }



  public TypeInfo declaringType(Type declaringType) {
    this.declaringType = declaringType;
    return this;
  }

  /**
   * Get declaringType
   * @return declaringType
   */
  @javax.annotation.Nullable
  public Type getDeclaringType() {
    return declaringType;
  }

  public void setDeclaringType(Type declaringType) {
    this.declaringType = declaringType;
  }


  public TypeInfo declaringMethod(MethodBase declaringMethod) {
    this.declaringMethod = declaringMethod;
    return this;
  }

  /**
   * Get declaringMethod
   * @return declaringMethod
   */
  @javax.annotation.Nullable
  public MethodBase getDeclaringMethod() {
    return declaringMethod;
  }

  public void setDeclaringMethod(MethodBase declaringMethod) {
    this.declaringMethod = declaringMethod;
  }


  public TypeInfo reflectedType(Type reflectedType) {
    this.reflectedType = reflectedType;
    return this;
  }

  /**
   * Get reflectedType
   * @return reflectedType
   */
  @javax.annotation.Nullable
  public Type getReflectedType() {
    return reflectedType;
  }

  public void setReflectedType(Type reflectedType) {
    this.reflectedType = reflectedType;
  }


  public TypeInfo underlyingSystemType(Type underlyingSystemType) {
    this.underlyingSystemType = underlyingSystemType;
    return this;
  }

  /**
   * Get underlyingSystemType
   * @return underlyingSystemType
   */
  @javax.annotation.Nullable
  public Type getUnderlyingSystemType() {
    return underlyingSystemType;
  }

  public void setUnderlyingSystemType(Type underlyingSystemType) {
    this.underlyingSystemType = underlyingSystemType;
  }


  /**
   * Get isTypeDefinition
   * @return isTypeDefinition
   */
  @javax.annotation.Nullable
  public Boolean getIsTypeDefinition() {
    return isTypeDefinition;
  }



  /**
   * Get isArray
   * @return isArray
   */
  @javax.annotation.Nullable
  public Boolean getIsArray() {
    return isArray;
  }



  /**
   * Get isByRef
   * @return isByRef
   */
  @javax.annotation.Nullable
  public Boolean getIsByRef() {
    return isByRef;
  }



  /**
   * Get isPointer
   * @return isPointer
   */
  @javax.annotation.Nullable
  public Boolean getIsPointer() {
    return isPointer;
  }



  /**
   * Get isConstructedGenericType
   * @return isConstructedGenericType
   */
  @javax.annotation.Nullable
  public Boolean getIsConstructedGenericType() {
    return isConstructedGenericType;
  }



  /**
   * Get isGenericParameter
   * @return isGenericParameter
   */
  @javax.annotation.Nullable
  public Boolean getIsGenericParameter() {
    return isGenericParameter;
  }



  /**
   * Get isGenericTypeParameter
   * @return isGenericTypeParameter
   */
  @javax.annotation.Nullable
  public Boolean getIsGenericTypeParameter() {
    return isGenericTypeParameter;
  }



  /**
   * Get isGenericMethodParameter
   * @return isGenericMethodParameter
   */
  @javax.annotation.Nullable
  public Boolean getIsGenericMethodParameter() {
    return isGenericMethodParameter;
  }



  /**
   * Get isGenericType
   * @return isGenericType
   */
  @javax.annotation.Nullable
  public Boolean getIsGenericType() {
    return isGenericType;
  }



  /**
   * Get isGenericTypeDefinition
   * @return isGenericTypeDefinition
   */
  @javax.annotation.Nullable
  public Boolean getIsGenericTypeDefinition() {
    return isGenericTypeDefinition;
  }



  /**
   * Get isSZArray
   * @return isSZArray
   */
  @javax.annotation.Nullable
  public Boolean getIsSZArray() {
    return isSZArray;
  }



  /**
   * Get isVariableBoundArray
   * @return isVariableBoundArray
   */
  @javax.annotation.Nullable
  public Boolean getIsVariableBoundArray() {
    return isVariableBoundArray;
  }



  /**
   * Get isByRefLike
   * @return isByRefLike
   */
  @javax.annotation.Nullable
  public Boolean getIsByRefLike() {
    return isByRefLike;
  }



  /**
   * Get isFunctionPointer
   * @return isFunctionPointer
   */
  @javax.annotation.Nullable
  public Boolean getIsFunctionPointer() {
    return isFunctionPointer;
  }



  /**
   * Get isUnmanagedFunctionPointer
   * @return isUnmanagedFunctionPointer
   */
  @javax.annotation.Nullable
  public Boolean getIsUnmanagedFunctionPointer() {
    return isUnmanagedFunctionPointer;
  }



  /**
   * Get hasElementType
   * @return hasElementType
   */
  @javax.annotation.Nullable
  public Boolean getHasElementType() {
    return hasElementType;
  }



  /**
   * Get genericTypeArguments
   * @return genericTypeArguments
   */
  @javax.annotation.Nullable
  public List<Type> getGenericTypeArguments() {
    return genericTypeArguments;
  }



  /**
   * Get genericParameterPosition
   * @return genericParameterPosition
   */
  @javax.annotation.Nullable
  public Integer getGenericParameterPosition() {
    return genericParameterPosition;
  }



  /**
   * Get genericParameterAttributes
   * @return genericParameterAttributes
   */
  @javax.annotation.Nullable
  public GenericParameterAttributesEnum getGenericParameterAttributes() {
    return genericParameterAttributes;
  }



  /**
   * Get attributes
   * @return attributes
   */
  @javax.annotation.Nullable
  public AttributesEnum getAttributes() {
    return attributes;
  }



  /**
   * Get isAbstract
   * @return isAbstract
   */
  @javax.annotation.Nullable
  public Boolean getIsAbstract() {
    return isAbstract;
  }



  /**
   * Get isImport
   * @return isImport
   */
  @javax.annotation.Nullable
  public Boolean getIsImport() {
    return isImport;
  }



  /**
   * Get isSealed
   * @return isSealed
   */
  @javax.annotation.Nullable
  public Boolean getIsSealed() {
    return isSealed;
  }



  /**
   * Get isSpecialName
   * @return isSpecialName
   */
  @javax.annotation.Nullable
  public Boolean getIsSpecialName() {
    return isSpecialName;
  }



  /**
   * Get isClass
   * @return isClass
   */
  @javax.annotation.Nullable
  public Boolean getIsClass() {
    return isClass;
  }



  /**
   * Get isNestedAssembly
   * @return isNestedAssembly
   */
  @javax.annotation.Nullable
  public Boolean getIsNestedAssembly() {
    return isNestedAssembly;
  }



  /**
   * Get isNestedFamANDAssem
   * @return isNestedFamANDAssem
   */
  @javax.annotation.Nullable
  public Boolean getIsNestedFamANDAssem() {
    return isNestedFamANDAssem;
  }



  /**
   * Get isNestedFamily
   * @return isNestedFamily
   */
  @javax.annotation.Nullable
  public Boolean getIsNestedFamily() {
    return isNestedFamily;
  }



  /**
   * Get isNestedFamORAssem
   * @return isNestedFamORAssem
   */
  @javax.annotation.Nullable
  public Boolean getIsNestedFamORAssem() {
    return isNestedFamORAssem;
  }



  /**
   * Get isNestedPrivate
   * @return isNestedPrivate
   */
  @javax.annotation.Nullable
  public Boolean getIsNestedPrivate() {
    return isNestedPrivate;
  }



  /**
   * Get isNestedPublic
   * @return isNestedPublic
   */
  @javax.annotation.Nullable
  public Boolean getIsNestedPublic() {
    return isNestedPublic;
  }



  /**
   * Get isNotPublic
   * @return isNotPublic
   */
  @javax.annotation.Nullable
  public Boolean getIsNotPublic() {
    return isNotPublic;
  }



  /**
   * Get isPublic
   * @return isPublic
   */
  @javax.annotation.Nullable
  public Boolean getIsPublic() {
    return isPublic;
  }



  /**
   * Get isAutoLayout
   * @return isAutoLayout
   */
  @javax.annotation.Nullable
  public Boolean getIsAutoLayout() {
    return isAutoLayout;
  }



  /**
   * Get isExplicitLayout
   * @return isExplicitLayout
   */
  @javax.annotation.Nullable
  public Boolean getIsExplicitLayout() {
    return isExplicitLayout;
  }



  /**
   * Get isLayoutSequential
   * @return isLayoutSequential
   */
  @javax.annotation.Nullable
  public Boolean getIsLayoutSequential() {
    return isLayoutSequential;
  }



  /**
   * Get isAnsiClass
   * @return isAnsiClass
   */
  @javax.annotation.Nullable
  public Boolean getIsAnsiClass() {
    return isAnsiClass;
  }



  /**
   * Get isAutoClass
   * @return isAutoClass
   */
  @javax.annotation.Nullable
  public Boolean getIsAutoClass() {
    return isAutoClass;
  }



  /**
   * Get isUnicodeClass
   * @return isUnicodeClass
   */
  @javax.annotation.Nullable
  public Boolean getIsUnicodeClass() {
    return isUnicodeClass;
  }



  /**
   * Get isCOMObject
   * @return isCOMObject
   */
  @javax.annotation.Nullable
  public Boolean getIsCOMObject() {
    return isCOMObject;
  }



  /**
   * Get isContextful
   * @return isContextful
   */
  @javax.annotation.Nullable
  public Boolean getIsContextful() {
    return isContextful;
  }



  /**
   * Get isEnum
   * @return isEnum
   */
  @javax.annotation.Nullable
  public Boolean getIsEnum() {
    return isEnum;
  }



  /**
   * Get isMarshalByRef
   * @return isMarshalByRef
   */
  @javax.annotation.Nullable
  public Boolean getIsMarshalByRef() {
    return isMarshalByRef;
  }



  /**
   * Get isPrimitive
   * @return isPrimitive
   */
  @javax.annotation.Nullable
  public Boolean getIsPrimitive() {
    return isPrimitive;
  }



  /**
   * Get isValueType
   * @return isValueType
   */
  @javax.annotation.Nullable
  public Boolean getIsValueType() {
    return isValueType;
  }



  /**
   * Get isSignatureType
   * @return isSignatureType
   */
  @javax.annotation.Nullable
  public Boolean getIsSignatureType() {
    return isSignatureType;
  }



  /**
   * Get isSecurityCritical
   * @return isSecurityCritical
   */
  @javax.annotation.Nullable
  public Boolean getIsSecurityCritical() {
    return isSecurityCritical;
  }



  /**
   * Get isSecuritySafeCritical
   * @return isSecuritySafeCritical
   */
  @javax.annotation.Nullable
  public Boolean getIsSecuritySafeCritical() {
    return isSecuritySafeCritical;
  }



  /**
   * Get isSecurityTransparent
   * @return isSecurityTransparent
   */
  @javax.annotation.Nullable
  public Boolean getIsSecurityTransparent() {
    return isSecurityTransparent;
  }



  public TypeInfo structLayoutAttribute(StructLayoutAttribute structLayoutAttribute) {
    this.structLayoutAttribute = structLayoutAttribute;
    return this;
  }

  /**
   * Get structLayoutAttribute
   * @return structLayoutAttribute
   */
  @javax.annotation.Nullable
  public StructLayoutAttribute getStructLayoutAttribute() {
    return structLayoutAttribute;
  }

  public void setStructLayoutAttribute(StructLayoutAttribute structLayoutAttribute) {
    this.structLayoutAttribute = structLayoutAttribute;
  }


  public TypeInfo typeInitializer(ConstructorInfo typeInitializer) {
    this.typeInitializer = typeInitializer;
    return this;
  }

  /**
   * Get typeInitializer
   * @return typeInitializer
   */
  @javax.annotation.Nullable
  public ConstructorInfo getTypeInitializer() {
    return typeInitializer;
  }

  public void setTypeInitializer(ConstructorInfo typeInitializer) {
    this.typeInitializer = typeInitializer;
  }


  public TypeInfo typeHandle(RuntimeTypeHandle typeHandle) {
    this.typeHandle = typeHandle;
    return this;
  }

  /**
   * Get typeHandle
   * @return typeHandle
   */
  @javax.annotation.Nullable
  public RuntimeTypeHandle getTypeHandle() {
    return typeHandle;
  }

  public void setTypeHandle(RuntimeTypeHandle typeHandle) {
    this.typeHandle = typeHandle;
  }


  /**
   * Get guid
   * @return guid
   */
  @javax.annotation.Nullable
  public UUID getGuid() {
    return guid;
  }



  public TypeInfo baseType(Type baseType) {
    this.baseType = baseType;
    return this;
  }

  /**
   * Get baseType
   * @return baseType
   */
  @javax.annotation.Nullable
  public Type getBaseType() {
    return baseType;
  }

  public void setBaseType(Type baseType) {
    this.baseType = baseType;
  }


  /**
   * Get isSerializable
   * @return isSerializable
   * @deprecated
   */
  @Deprecated
  @javax.annotation.Nullable
  public Boolean getIsSerializable() {
    return isSerializable;
  }



  /**
   * Get containsGenericParameters
   * @return containsGenericParameters
   */
  @javax.annotation.Nullable
  public Boolean getContainsGenericParameters() {
    return containsGenericParameters;
  }



  /**
   * Get isVisible
   * @return isVisible
   */
  @javax.annotation.Nullable
  public Boolean getIsVisible() {
    return isVisible;
  }



  /**
   * Get genericTypeParameters
   * @return genericTypeParameters
   */
  @javax.annotation.Nullable
  public List<Type> getGenericTypeParameters() {
    return genericTypeParameters;
  }



  /**
   * Get declaredConstructors
   * @return declaredConstructors
   */
  @javax.annotation.Nullable
  public List<ConstructorInfo> getDeclaredConstructors() {
    return declaredConstructors;
  }



  /**
   * Get declaredEvents
   * @return declaredEvents
   */
  @javax.annotation.Nullable
  public List<EventInfo> getDeclaredEvents() {
    return declaredEvents;
  }



  /**
   * Get declaredFields
   * @return declaredFields
   */
  @javax.annotation.Nullable
  public List<FieldInfo> getDeclaredFields() {
    return declaredFields;
  }



  /**
   * Get declaredMembers
   * @return declaredMembers
   */
  @javax.annotation.Nullable
  public List<MemberInfo> getDeclaredMembers() {
    return declaredMembers;
  }



  /**
   * Get declaredMethods
   * @return declaredMethods
   */
  @javax.annotation.Nullable
  public List<MethodInfo> getDeclaredMethods() {
    return declaredMethods;
  }



  /**
   * Get declaredNestedTypes
   * @return declaredNestedTypes
   */
  @javax.annotation.Nullable
  public List<TypeInfo> getDeclaredNestedTypes() {
    return declaredNestedTypes;
  }



  /**
   * Get declaredProperties
   * @return declaredProperties
   */
  @javax.annotation.Nullable
  public List<PropertyInfo> getDeclaredProperties() {
    return declaredProperties;
  }



  /**
   * Get implementedInterfaces
   * @return implementedInterfaces
   */
  @javax.annotation.Nullable
  public List<Type> getImplementedInterfaces() {
    return implementedInterfaces;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TypeInfo typeInfo = (TypeInfo) o;
    return Objects.equals(this.name, typeInfo.name) &&
        Objects.equals(this.customAttributes, typeInfo.customAttributes) &&
        Objects.equals(this.isCollectible, typeInfo.isCollectible) &&
        Objects.equals(this.metadataToken, typeInfo.metadataToken) &&
        Objects.equals(this.memberType, typeInfo.memberType) &&
        Objects.equals(this.namespace, typeInfo.namespace) &&
        Objects.equals(this.assemblyQualifiedName, typeInfo.assemblyQualifiedName) &&
        Objects.equals(this.fullName, typeInfo.fullName) &&
        Objects.equals(this.assembly, typeInfo.assembly) &&
        Objects.equals(this.module, typeInfo.module) &&
        Objects.equals(this.isInterface, typeInfo.isInterface) &&
        Objects.equals(this.isNested, typeInfo.isNested) &&
        Objects.equals(this.declaringType, typeInfo.declaringType) &&
        Objects.equals(this.declaringMethod, typeInfo.declaringMethod) &&
        Objects.equals(this.reflectedType, typeInfo.reflectedType) &&
        Objects.equals(this.underlyingSystemType, typeInfo.underlyingSystemType) &&
        Objects.equals(this.isTypeDefinition, typeInfo.isTypeDefinition) &&
        Objects.equals(this.isArray, typeInfo.isArray) &&
        Objects.equals(this.isByRef, typeInfo.isByRef) &&
        Objects.equals(this.isPointer, typeInfo.isPointer) &&
        Objects.equals(this.isConstructedGenericType, typeInfo.isConstructedGenericType) &&
        Objects.equals(this.isGenericParameter, typeInfo.isGenericParameter) &&
        Objects.equals(this.isGenericTypeParameter, typeInfo.isGenericTypeParameter) &&
        Objects.equals(this.isGenericMethodParameter, typeInfo.isGenericMethodParameter) &&
        Objects.equals(this.isGenericType, typeInfo.isGenericType) &&
        Objects.equals(this.isGenericTypeDefinition, typeInfo.isGenericTypeDefinition) &&
        Objects.equals(this.isSZArray, typeInfo.isSZArray) &&
        Objects.equals(this.isVariableBoundArray, typeInfo.isVariableBoundArray) &&
        Objects.equals(this.isByRefLike, typeInfo.isByRefLike) &&
        Objects.equals(this.isFunctionPointer, typeInfo.isFunctionPointer) &&
        Objects.equals(this.isUnmanagedFunctionPointer, typeInfo.isUnmanagedFunctionPointer) &&
        Objects.equals(this.hasElementType, typeInfo.hasElementType) &&
        Objects.equals(this.genericTypeArguments, typeInfo.genericTypeArguments) &&
        Objects.equals(this.genericParameterPosition, typeInfo.genericParameterPosition) &&
        Objects.equals(this.genericParameterAttributes, typeInfo.genericParameterAttributes) &&
        Objects.equals(this.attributes, typeInfo.attributes) &&
        Objects.equals(this.isAbstract, typeInfo.isAbstract) &&
        Objects.equals(this.isImport, typeInfo.isImport) &&
        Objects.equals(this.isSealed, typeInfo.isSealed) &&
        Objects.equals(this.isSpecialName, typeInfo.isSpecialName) &&
        Objects.equals(this.isClass, typeInfo.isClass) &&
        Objects.equals(this.isNestedAssembly, typeInfo.isNestedAssembly) &&
        Objects.equals(this.isNestedFamANDAssem, typeInfo.isNestedFamANDAssem) &&
        Objects.equals(this.isNestedFamily, typeInfo.isNestedFamily) &&
        Objects.equals(this.isNestedFamORAssem, typeInfo.isNestedFamORAssem) &&
        Objects.equals(this.isNestedPrivate, typeInfo.isNestedPrivate) &&
        Objects.equals(this.isNestedPublic, typeInfo.isNestedPublic) &&
        Objects.equals(this.isNotPublic, typeInfo.isNotPublic) &&
        Objects.equals(this.isPublic, typeInfo.isPublic) &&
        Objects.equals(this.isAutoLayout, typeInfo.isAutoLayout) &&
        Objects.equals(this.isExplicitLayout, typeInfo.isExplicitLayout) &&
        Objects.equals(this.isLayoutSequential, typeInfo.isLayoutSequential) &&
        Objects.equals(this.isAnsiClass, typeInfo.isAnsiClass) &&
        Objects.equals(this.isAutoClass, typeInfo.isAutoClass) &&
        Objects.equals(this.isUnicodeClass, typeInfo.isUnicodeClass) &&
        Objects.equals(this.isCOMObject, typeInfo.isCOMObject) &&
        Objects.equals(this.isContextful, typeInfo.isContextful) &&
        Objects.equals(this.isEnum, typeInfo.isEnum) &&
        Objects.equals(this.isMarshalByRef, typeInfo.isMarshalByRef) &&
        Objects.equals(this.isPrimitive, typeInfo.isPrimitive) &&
        Objects.equals(this.isValueType, typeInfo.isValueType) &&
        Objects.equals(this.isSignatureType, typeInfo.isSignatureType) &&
        Objects.equals(this.isSecurityCritical, typeInfo.isSecurityCritical) &&
        Objects.equals(this.isSecuritySafeCritical, typeInfo.isSecuritySafeCritical) &&
        Objects.equals(this.isSecurityTransparent, typeInfo.isSecurityTransparent) &&
        Objects.equals(this.structLayoutAttribute, typeInfo.structLayoutAttribute) &&
        Objects.equals(this.typeInitializer, typeInfo.typeInitializer) &&
        Objects.equals(this.typeHandle, typeInfo.typeHandle) &&
        Objects.equals(this.guid, typeInfo.guid) &&
        Objects.equals(this.baseType, typeInfo.baseType) &&
        Objects.equals(this.isSerializable, typeInfo.isSerializable) &&
        Objects.equals(this.containsGenericParameters, typeInfo.containsGenericParameters) &&
        Objects.equals(this.isVisible, typeInfo.isVisible) &&
        Objects.equals(this.genericTypeParameters, typeInfo.genericTypeParameters) &&
        Objects.equals(this.declaredConstructors, typeInfo.declaredConstructors) &&
        Objects.equals(this.declaredEvents, typeInfo.declaredEvents) &&
        Objects.equals(this.declaredFields, typeInfo.declaredFields) &&
        Objects.equals(this.declaredMembers, typeInfo.declaredMembers) &&
        Objects.equals(this.declaredMethods, typeInfo.declaredMethods) &&
        Objects.equals(this.declaredNestedTypes, typeInfo.declaredNestedTypes) &&
        Objects.equals(this.declaredProperties, typeInfo.declaredProperties) &&
        Objects.equals(this.implementedInterfaces, typeInfo.implementedInterfaces);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, customAttributes, isCollectible, metadataToken, memberType, namespace, assemblyQualifiedName, fullName, assembly, module, isInterface, isNested, declaringType, declaringMethod, reflectedType, underlyingSystemType, isTypeDefinition, isArray, isByRef, isPointer, isConstructedGenericType, isGenericParameter, isGenericTypeParameter, isGenericMethodParameter, isGenericType, isGenericTypeDefinition, isSZArray, isVariableBoundArray, isByRefLike, isFunctionPointer, isUnmanagedFunctionPointer, hasElementType, genericTypeArguments, genericParameterPosition, genericParameterAttributes, attributes, isAbstract, isImport, isSealed, isSpecialName, isClass, isNestedAssembly, isNestedFamANDAssem, isNestedFamily, isNestedFamORAssem, isNestedPrivate, isNestedPublic, isNotPublic, isPublic, isAutoLayout, isExplicitLayout, isLayoutSequential, isAnsiClass, isAutoClass, isUnicodeClass, isCOMObject, isContextful, isEnum, isMarshalByRef, isPrimitive, isValueType, isSignatureType, isSecurityCritical, isSecuritySafeCritical, isSecurityTransparent, structLayoutAttribute, typeInitializer, typeHandle, guid, baseType, isSerializable, containsGenericParameters, isVisible, genericTypeParameters, declaredConstructors, declaredEvents, declaredFields, declaredMembers, declaredMethods, declaredNestedTypes, declaredProperties, implementedInterfaces);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TypeInfo {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    customAttributes: ").append(toIndentedString(customAttributes)).append("\n");
    sb.append("    isCollectible: ").append(toIndentedString(isCollectible)).append("\n");
    sb.append("    metadataToken: ").append(toIndentedString(metadataToken)).append("\n");
    sb.append("    memberType: ").append(toIndentedString(memberType)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    assemblyQualifiedName: ").append(toIndentedString(assemblyQualifiedName)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    assembly: ").append(toIndentedString(assembly)).append("\n");
    sb.append("    module: ").append(toIndentedString(module)).append("\n");
    sb.append("    isInterface: ").append(toIndentedString(isInterface)).append("\n");
    sb.append("    isNested: ").append(toIndentedString(isNested)).append("\n");
    sb.append("    declaringType: ").append(toIndentedString(declaringType)).append("\n");
    sb.append("    declaringMethod: ").append(toIndentedString(declaringMethod)).append("\n");
    sb.append("    reflectedType: ").append(toIndentedString(reflectedType)).append("\n");
    sb.append("    underlyingSystemType: ").append(toIndentedString(underlyingSystemType)).append("\n");
    sb.append("    isTypeDefinition: ").append(toIndentedString(isTypeDefinition)).append("\n");
    sb.append("    isArray: ").append(toIndentedString(isArray)).append("\n");
    sb.append("    isByRef: ").append(toIndentedString(isByRef)).append("\n");
    sb.append("    isPointer: ").append(toIndentedString(isPointer)).append("\n");
    sb.append("    isConstructedGenericType: ").append(toIndentedString(isConstructedGenericType)).append("\n");
    sb.append("    isGenericParameter: ").append(toIndentedString(isGenericParameter)).append("\n");
    sb.append("    isGenericTypeParameter: ").append(toIndentedString(isGenericTypeParameter)).append("\n");
    sb.append("    isGenericMethodParameter: ").append(toIndentedString(isGenericMethodParameter)).append("\n");
    sb.append("    isGenericType: ").append(toIndentedString(isGenericType)).append("\n");
    sb.append("    isGenericTypeDefinition: ").append(toIndentedString(isGenericTypeDefinition)).append("\n");
    sb.append("    isSZArray: ").append(toIndentedString(isSZArray)).append("\n");
    sb.append("    isVariableBoundArray: ").append(toIndentedString(isVariableBoundArray)).append("\n");
    sb.append("    isByRefLike: ").append(toIndentedString(isByRefLike)).append("\n");
    sb.append("    isFunctionPointer: ").append(toIndentedString(isFunctionPointer)).append("\n");
    sb.append("    isUnmanagedFunctionPointer: ").append(toIndentedString(isUnmanagedFunctionPointer)).append("\n");
    sb.append("    hasElementType: ").append(toIndentedString(hasElementType)).append("\n");
    sb.append("    genericTypeArguments: ").append(toIndentedString(genericTypeArguments)).append("\n");
    sb.append("    genericParameterPosition: ").append(toIndentedString(genericParameterPosition)).append("\n");
    sb.append("    genericParameterAttributes: ").append(toIndentedString(genericParameterAttributes)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    isAbstract: ").append(toIndentedString(isAbstract)).append("\n");
    sb.append("    isImport: ").append(toIndentedString(isImport)).append("\n");
    sb.append("    isSealed: ").append(toIndentedString(isSealed)).append("\n");
    sb.append("    isSpecialName: ").append(toIndentedString(isSpecialName)).append("\n");
    sb.append("    isClass: ").append(toIndentedString(isClass)).append("\n");
    sb.append("    isNestedAssembly: ").append(toIndentedString(isNestedAssembly)).append("\n");
    sb.append("    isNestedFamANDAssem: ").append(toIndentedString(isNestedFamANDAssem)).append("\n");
    sb.append("    isNestedFamily: ").append(toIndentedString(isNestedFamily)).append("\n");
    sb.append("    isNestedFamORAssem: ").append(toIndentedString(isNestedFamORAssem)).append("\n");
    sb.append("    isNestedPrivate: ").append(toIndentedString(isNestedPrivate)).append("\n");
    sb.append("    isNestedPublic: ").append(toIndentedString(isNestedPublic)).append("\n");
    sb.append("    isNotPublic: ").append(toIndentedString(isNotPublic)).append("\n");
    sb.append("    isPublic: ").append(toIndentedString(isPublic)).append("\n");
    sb.append("    isAutoLayout: ").append(toIndentedString(isAutoLayout)).append("\n");
    sb.append("    isExplicitLayout: ").append(toIndentedString(isExplicitLayout)).append("\n");
    sb.append("    isLayoutSequential: ").append(toIndentedString(isLayoutSequential)).append("\n");
    sb.append("    isAnsiClass: ").append(toIndentedString(isAnsiClass)).append("\n");
    sb.append("    isAutoClass: ").append(toIndentedString(isAutoClass)).append("\n");
    sb.append("    isUnicodeClass: ").append(toIndentedString(isUnicodeClass)).append("\n");
    sb.append("    isCOMObject: ").append(toIndentedString(isCOMObject)).append("\n");
    sb.append("    isContextful: ").append(toIndentedString(isContextful)).append("\n");
    sb.append("    isEnum: ").append(toIndentedString(isEnum)).append("\n");
    sb.append("    isMarshalByRef: ").append(toIndentedString(isMarshalByRef)).append("\n");
    sb.append("    isPrimitive: ").append(toIndentedString(isPrimitive)).append("\n");
    sb.append("    isValueType: ").append(toIndentedString(isValueType)).append("\n");
    sb.append("    isSignatureType: ").append(toIndentedString(isSignatureType)).append("\n");
    sb.append("    isSecurityCritical: ").append(toIndentedString(isSecurityCritical)).append("\n");
    sb.append("    isSecuritySafeCritical: ").append(toIndentedString(isSecuritySafeCritical)).append("\n");
    sb.append("    isSecurityTransparent: ").append(toIndentedString(isSecurityTransparent)).append("\n");
    sb.append("    structLayoutAttribute: ").append(toIndentedString(structLayoutAttribute)).append("\n");
    sb.append("    typeInitializer: ").append(toIndentedString(typeInitializer)).append("\n");
    sb.append("    typeHandle: ").append(toIndentedString(typeHandle)).append("\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("    baseType: ").append(toIndentedString(baseType)).append("\n");
    sb.append("    isSerializable: ").append(toIndentedString(isSerializable)).append("\n");
    sb.append("    containsGenericParameters: ").append(toIndentedString(containsGenericParameters)).append("\n");
    sb.append("    isVisible: ").append(toIndentedString(isVisible)).append("\n");
    sb.append("    genericTypeParameters: ").append(toIndentedString(genericTypeParameters)).append("\n");
    sb.append("    declaredConstructors: ").append(toIndentedString(declaredConstructors)).append("\n");
    sb.append("    declaredEvents: ").append(toIndentedString(declaredEvents)).append("\n");
    sb.append("    declaredFields: ").append(toIndentedString(declaredFields)).append("\n");
    sb.append("    declaredMembers: ").append(toIndentedString(declaredMembers)).append("\n");
    sb.append("    declaredMethods: ").append(toIndentedString(declaredMethods)).append("\n");
    sb.append("    declaredNestedTypes: ").append(toIndentedString(declaredNestedTypes)).append("\n");
    sb.append("    declaredProperties: ").append(toIndentedString(declaredProperties)).append("\n");
    sb.append("    implementedInterfaces: ").append(toIndentedString(implementedInterfaces)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("customAttributes");
    openapiFields.add("isCollectible");
    openapiFields.add("metadataToken");
    openapiFields.add("memberType");
    openapiFields.add("namespace");
    openapiFields.add("assemblyQualifiedName");
    openapiFields.add("fullName");
    openapiFields.add("assembly");
    openapiFields.add("module");
    openapiFields.add("isInterface");
    openapiFields.add("isNested");
    openapiFields.add("declaringType");
    openapiFields.add("declaringMethod");
    openapiFields.add("reflectedType");
    openapiFields.add("underlyingSystemType");
    openapiFields.add("isTypeDefinition");
    openapiFields.add("isArray");
    openapiFields.add("isByRef");
    openapiFields.add("isPointer");
    openapiFields.add("isConstructedGenericType");
    openapiFields.add("isGenericParameter");
    openapiFields.add("isGenericTypeParameter");
    openapiFields.add("isGenericMethodParameter");
    openapiFields.add("isGenericType");
    openapiFields.add("isGenericTypeDefinition");
    openapiFields.add("isSZArray");
    openapiFields.add("isVariableBoundArray");
    openapiFields.add("isByRefLike");
    openapiFields.add("isFunctionPointer");
    openapiFields.add("isUnmanagedFunctionPointer");
    openapiFields.add("hasElementType");
    openapiFields.add("genericTypeArguments");
    openapiFields.add("genericParameterPosition");
    openapiFields.add("genericParameterAttributes");
    openapiFields.add("attributes");
    openapiFields.add("isAbstract");
    openapiFields.add("isImport");
    openapiFields.add("isSealed");
    openapiFields.add("isSpecialName");
    openapiFields.add("isClass");
    openapiFields.add("isNestedAssembly");
    openapiFields.add("isNestedFamANDAssem");
    openapiFields.add("isNestedFamily");
    openapiFields.add("isNestedFamORAssem");
    openapiFields.add("isNestedPrivate");
    openapiFields.add("isNestedPublic");
    openapiFields.add("isNotPublic");
    openapiFields.add("isPublic");
    openapiFields.add("isAutoLayout");
    openapiFields.add("isExplicitLayout");
    openapiFields.add("isLayoutSequential");
    openapiFields.add("isAnsiClass");
    openapiFields.add("isAutoClass");
    openapiFields.add("isUnicodeClass");
    openapiFields.add("isCOMObject");
    openapiFields.add("isContextful");
    openapiFields.add("isEnum");
    openapiFields.add("isMarshalByRef");
    openapiFields.add("isPrimitive");
    openapiFields.add("isValueType");
    openapiFields.add("isSignatureType");
    openapiFields.add("isSecurityCritical");
    openapiFields.add("isSecuritySafeCritical");
    openapiFields.add("isSecurityTransparent");
    openapiFields.add("structLayoutAttribute");
    openapiFields.add("typeInitializer");
    openapiFields.add("typeHandle");
    openapiFields.add("guid");
    openapiFields.add("baseType");
    openapiFields.add("isSerializable");
    openapiFields.add("containsGenericParameters");
    openapiFields.add("isVisible");
    openapiFields.add("genericTypeParameters");
    openapiFields.add("declaredConstructors");
    openapiFields.add("declaredEvents");
    openapiFields.add("declaredFields");
    openapiFields.add("declaredMembers");
    openapiFields.add("declaredMethods");
    openapiFields.add("declaredNestedTypes");
    openapiFields.add("declaredProperties");
    openapiFields.add("implementedInterfaces");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TypeInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TypeInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TypeInfo is not found in the empty JSON string", TypeInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TypeInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TypeInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (jsonObj.get("customAttributes") != null && !jsonObj.get("customAttributes").isJsonNull()) {
        JsonArray jsonArraycustomAttributes = jsonObj.getAsJsonArray("customAttributes");
        if (jsonArraycustomAttributes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("customAttributes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `customAttributes` to be an array in the JSON string but got `%s`", jsonObj.get("customAttributes").toString()));
          }

          // validate the optional field `customAttributes` (array)
          for (int i = 0; i < jsonArraycustomAttributes.size(); i++) {
            CustomAttributeData.validateJsonElement(jsonArraycustomAttributes.get(i));
          };
        }
      }
      if ((jsonObj.get("memberType") != null && !jsonObj.get("memberType").isJsonNull()) && !jsonObj.get("memberType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `memberType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("memberType").toString()));
      }
      // validate the optional field `memberType`
      if (jsonObj.get("memberType") != null && !jsonObj.get("memberType").isJsonNull()) {
        MemberTypeEnum.validateJsonElement(jsonObj.get("memberType"));
      }
      if ((jsonObj.get("namespace") != null && !jsonObj.get("namespace").isJsonNull()) && !jsonObj.get("namespace").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `namespace` to be a primitive type in the JSON string but got `%s`", jsonObj.get("namespace").toString()));
      }
      if ((jsonObj.get("assemblyQualifiedName") != null && !jsonObj.get("assemblyQualifiedName").isJsonNull()) && !jsonObj.get("assemblyQualifiedName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `assemblyQualifiedName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("assemblyQualifiedName").toString()));
      }
      if ((jsonObj.get("fullName") != null && !jsonObj.get("fullName").isJsonNull()) && !jsonObj.get("fullName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fullName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fullName").toString()));
      }
      // validate the optional field `assembly`
      if (jsonObj.get("assembly") != null && !jsonObj.get("assembly").isJsonNull()) {
        Assembly.validateJsonElement(jsonObj.get("assembly"));
      }
      // validate the optional field `module`
      if (jsonObj.get("module") != null && !jsonObj.get("module").isJsonNull()) {
        Module.validateJsonElement(jsonObj.get("module"));
      }
      // validate the optional field `declaringType`
      if (jsonObj.get("declaringType") != null && !jsonObj.get("declaringType").isJsonNull()) {
        Type.validateJsonElement(jsonObj.get("declaringType"));
      }
      // validate the optional field `declaringMethod`
      if (jsonObj.get("declaringMethod") != null && !jsonObj.get("declaringMethod").isJsonNull()) {
        MethodBase.validateJsonElement(jsonObj.get("declaringMethod"));
      }
      // validate the optional field `reflectedType`
      if (jsonObj.get("reflectedType") != null && !jsonObj.get("reflectedType").isJsonNull()) {
        Type.validateJsonElement(jsonObj.get("reflectedType"));
      }
      // validate the optional field `underlyingSystemType`
      if (jsonObj.get("underlyingSystemType") != null && !jsonObj.get("underlyingSystemType").isJsonNull()) {
        Type.validateJsonElement(jsonObj.get("underlyingSystemType"));
      }
      if (jsonObj.get("genericTypeArguments") != null && !jsonObj.get("genericTypeArguments").isJsonNull()) {
        JsonArray jsonArraygenericTypeArguments = jsonObj.getAsJsonArray("genericTypeArguments");
        if (jsonArraygenericTypeArguments != null) {
          // ensure the json data is an array
          if (!jsonObj.get("genericTypeArguments").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `genericTypeArguments` to be an array in the JSON string but got `%s`", jsonObj.get("genericTypeArguments").toString()));
          }

          // validate the optional field `genericTypeArguments` (array)
          for (int i = 0; i < jsonArraygenericTypeArguments.size(); i++) {
            Type.validateJsonElement(jsonArraygenericTypeArguments.get(i));
          };
        }
      }
      if ((jsonObj.get("genericParameterAttributes") != null && !jsonObj.get("genericParameterAttributes").isJsonNull()) && !jsonObj.get("genericParameterAttributes").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `genericParameterAttributes` to be a primitive type in the JSON string but got `%s`", jsonObj.get("genericParameterAttributes").toString()));
      }
      // validate the optional field `genericParameterAttributes`
      if (jsonObj.get("genericParameterAttributes") != null && !jsonObj.get("genericParameterAttributes").isJsonNull()) {
        GenericParameterAttributesEnum.validateJsonElement(jsonObj.get("genericParameterAttributes"));
      }
      if ((jsonObj.get("attributes") != null && !jsonObj.get("attributes").isJsonNull()) && !jsonObj.get("attributes").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `attributes` to be a primitive type in the JSON string but got `%s`", jsonObj.get("attributes").toString()));
      }
      // validate the optional field `attributes`
      if (jsonObj.get("attributes") != null && !jsonObj.get("attributes").isJsonNull()) {
        AttributesEnum.validateJsonElement(jsonObj.get("attributes"));
      }
      // validate the optional field `structLayoutAttribute`
      if (jsonObj.get("structLayoutAttribute") != null && !jsonObj.get("structLayoutAttribute").isJsonNull()) {
        StructLayoutAttribute.validateJsonElement(jsonObj.get("structLayoutAttribute"));
      }
      // validate the optional field `typeInitializer`
      if (jsonObj.get("typeInitializer") != null && !jsonObj.get("typeInitializer").isJsonNull()) {
        ConstructorInfo.validateJsonElement(jsonObj.get("typeInitializer"));
      }
      // validate the optional field `typeHandle`
      if (jsonObj.get("typeHandle") != null && !jsonObj.get("typeHandle").isJsonNull()) {
        RuntimeTypeHandle.validateJsonElement(jsonObj.get("typeHandle"));
      }
      if ((jsonObj.get("guid") != null && !jsonObj.get("guid").isJsonNull()) && !jsonObj.get("guid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `guid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("guid").toString()));
      }
      // validate the optional field `baseType`
      if (jsonObj.get("baseType") != null && !jsonObj.get("baseType").isJsonNull()) {
        Type.validateJsonElement(jsonObj.get("baseType"));
      }
      if (jsonObj.get("genericTypeParameters") != null && !jsonObj.get("genericTypeParameters").isJsonNull()) {
        JsonArray jsonArraygenericTypeParameters = jsonObj.getAsJsonArray("genericTypeParameters");
        if (jsonArraygenericTypeParameters != null) {
          // ensure the json data is an array
          if (!jsonObj.get("genericTypeParameters").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `genericTypeParameters` to be an array in the JSON string but got `%s`", jsonObj.get("genericTypeParameters").toString()));
          }

          // validate the optional field `genericTypeParameters` (array)
          for (int i = 0; i < jsonArraygenericTypeParameters.size(); i++) {
            Type.validateJsonElement(jsonArraygenericTypeParameters.get(i));
          };
        }
      }
      if (jsonObj.get("declaredConstructors") != null && !jsonObj.get("declaredConstructors").isJsonNull()) {
        JsonArray jsonArraydeclaredConstructors = jsonObj.getAsJsonArray("declaredConstructors");
        if (jsonArraydeclaredConstructors != null) {
          // ensure the json data is an array
          if (!jsonObj.get("declaredConstructors").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `declaredConstructors` to be an array in the JSON string but got `%s`", jsonObj.get("declaredConstructors").toString()));
          }

          // validate the optional field `declaredConstructors` (array)
          for (int i = 0; i < jsonArraydeclaredConstructors.size(); i++) {
            ConstructorInfo.validateJsonElement(jsonArraydeclaredConstructors.get(i));
          };
        }
      }
      if (jsonObj.get("declaredEvents") != null && !jsonObj.get("declaredEvents").isJsonNull()) {
        JsonArray jsonArraydeclaredEvents = jsonObj.getAsJsonArray("declaredEvents");
        if (jsonArraydeclaredEvents != null) {
          // ensure the json data is an array
          if (!jsonObj.get("declaredEvents").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `declaredEvents` to be an array in the JSON string but got `%s`", jsonObj.get("declaredEvents").toString()));
          }

          // validate the optional field `declaredEvents` (array)
          for (int i = 0; i < jsonArraydeclaredEvents.size(); i++) {
            EventInfo.validateJsonElement(jsonArraydeclaredEvents.get(i));
          };
        }
      }
      if (jsonObj.get("declaredFields") != null && !jsonObj.get("declaredFields").isJsonNull()) {
        JsonArray jsonArraydeclaredFields = jsonObj.getAsJsonArray("declaredFields");
        if (jsonArraydeclaredFields != null) {
          // ensure the json data is an array
          if (!jsonObj.get("declaredFields").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `declaredFields` to be an array in the JSON string but got `%s`", jsonObj.get("declaredFields").toString()));
          }

          // validate the optional field `declaredFields` (array)
          for (int i = 0; i < jsonArraydeclaredFields.size(); i++) {
            FieldInfo.validateJsonElement(jsonArraydeclaredFields.get(i));
          };
        }
      }
      if (jsonObj.get("declaredMembers") != null && !jsonObj.get("declaredMembers").isJsonNull()) {
        JsonArray jsonArraydeclaredMembers = jsonObj.getAsJsonArray("declaredMembers");
        if (jsonArraydeclaredMembers != null) {
          // ensure the json data is an array
          if (!jsonObj.get("declaredMembers").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `declaredMembers` to be an array in the JSON string but got `%s`", jsonObj.get("declaredMembers").toString()));
          }

          // validate the optional field `declaredMembers` (array)
          for (int i = 0; i < jsonArraydeclaredMembers.size(); i++) {
            MemberInfo.validateJsonElement(jsonArraydeclaredMembers.get(i));
          };
        }
      }
      if (jsonObj.get("declaredMethods") != null && !jsonObj.get("declaredMethods").isJsonNull()) {
        JsonArray jsonArraydeclaredMethods = jsonObj.getAsJsonArray("declaredMethods");
        if (jsonArraydeclaredMethods != null) {
          // ensure the json data is an array
          if (!jsonObj.get("declaredMethods").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `declaredMethods` to be an array in the JSON string but got `%s`", jsonObj.get("declaredMethods").toString()));
          }

          // validate the optional field `declaredMethods` (array)
          for (int i = 0; i < jsonArraydeclaredMethods.size(); i++) {
            MethodInfo.validateJsonElement(jsonArraydeclaredMethods.get(i));
          };
        }
      }
      if (jsonObj.get("declaredNestedTypes") != null && !jsonObj.get("declaredNestedTypes").isJsonNull()) {
        JsonArray jsonArraydeclaredNestedTypes = jsonObj.getAsJsonArray("declaredNestedTypes");
        if (jsonArraydeclaredNestedTypes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("declaredNestedTypes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `declaredNestedTypes` to be an array in the JSON string but got `%s`", jsonObj.get("declaredNestedTypes").toString()));
          }

          // validate the optional field `declaredNestedTypes` (array)
          for (int i = 0; i < jsonArraydeclaredNestedTypes.size(); i++) {
            TypeInfo.validateJsonElement(jsonArraydeclaredNestedTypes.get(i));
          };
        }
      }
      if (jsonObj.get("declaredProperties") != null && !jsonObj.get("declaredProperties").isJsonNull()) {
        JsonArray jsonArraydeclaredProperties = jsonObj.getAsJsonArray("declaredProperties");
        if (jsonArraydeclaredProperties != null) {
          // ensure the json data is an array
          if (!jsonObj.get("declaredProperties").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `declaredProperties` to be an array in the JSON string but got `%s`", jsonObj.get("declaredProperties").toString()));
          }

          // validate the optional field `declaredProperties` (array)
          for (int i = 0; i < jsonArraydeclaredProperties.size(); i++) {
            PropertyInfo.validateJsonElement(jsonArraydeclaredProperties.get(i));
          };
        }
      }
      if (jsonObj.get("implementedInterfaces") != null && !jsonObj.get("implementedInterfaces").isJsonNull()) {
        JsonArray jsonArrayimplementedInterfaces = jsonObj.getAsJsonArray("implementedInterfaces");
        if (jsonArrayimplementedInterfaces != null) {
          // ensure the json data is an array
          if (!jsonObj.get("implementedInterfaces").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `implementedInterfaces` to be an array in the JSON string but got `%s`", jsonObj.get("implementedInterfaces").toString()));
          }

          // validate the optional field `implementedInterfaces` (array)
          for (int i = 0; i < jsonArrayimplementedInterfaces.size(); i++) {
            Type.validateJsonElement(jsonArrayimplementedInterfaces.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TypeInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TypeInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TypeInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TypeInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<TypeInfo>() {
           @Override
           public void write(JsonWriter out, TypeInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TypeInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TypeInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TypeInfo
   * @throws IOException if the JSON string is invalid with respect to TypeInfo
   */
  public static TypeInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TypeInfo.class);
  }

  /**
   * Convert an instance of TypeInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

