/*
 * LogisticsService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5401
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.WaybillLineDto;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * RailWaybillDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-30T19:50:29.995974400-05:00[America/Bogota]", comments = "Generator version: 7.9.0")
public class RailWaybillDto {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  private OffsetDateTime timestamp;

  public static final String SERIALIZED_NAME_DOCUMENT_NUMBER = "documentNumber";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_NUMBER)
  private String documentNumber;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_SHIPPER_CONTACT_ID = "shipperContactId";
  @SerializedName(SERIALIZED_NAME_SHIPPER_CONTACT_ID)
  private String shipperContactId;

  public static final String SERIALIZED_NAME_CONSIGNEE_CONTACT_ID = "consigneeContactId";
  @SerializedName(SERIALIZED_NAME_CONSIGNEE_CONTACT_ID)
  private String consigneeContactId;

  public static final String SERIALIZED_NAME_CARRIER_ID = "carrierId";
  @SerializedName(SERIALIZED_NAME_CARRIER_ID)
  private String carrierId;

  public static final String SERIALIZED_NAME_RAIL_OPERATOR_NAME = "railOperatorName";
  @SerializedName(SERIALIZED_NAME_RAIL_OPERATOR_NAME)
  private String railOperatorName;

  public static final String SERIALIZED_NAME_STATION_OF_DEPARTURE = "stationOfDeparture";
  @SerializedName(SERIALIZED_NAME_STATION_OF_DEPARTURE)
  private String stationOfDeparture;

  public static final String SERIALIZED_NAME_STATION_OF_DEPARTURE_CODE = "stationOfDepartureCode";
  @SerializedName(SERIALIZED_NAME_STATION_OF_DEPARTURE_CODE)
  private String stationOfDepartureCode;

  public static final String SERIALIZED_NAME_STATION_OF_DESTINATION = "stationOfDestination";
  @SerializedName(SERIALIZED_NAME_STATION_OF_DESTINATION)
  private String stationOfDestination;

  public static final String SERIALIZED_NAME_STATION_OF_DESTINATION_CODE = "stationOfDestinationCode";
  @SerializedName(SERIALIZED_NAME_STATION_OF_DESTINATION_CODE)
  private String stationOfDestinationCode;

  public static final String SERIALIZED_NAME_PRESCRIBED_ROUTE = "prescribedRoute";
  @SerializedName(SERIALIZED_NAME_PRESCRIBED_ROUTE)
  private String prescribedRoute;

  public static final String SERIALIZED_NAME_WAGON_NUMBERS = "wagonNumbers";
  @SerializedName(SERIALIZED_NAME_WAGON_NUMBERS)
  private String wagonNumbers;

  public static final String SERIALIZED_NAME_DATE_OF_ACCEPTANCE = "dateOfAcceptance";
  @SerializedName(SERIALIZED_NAME_DATE_OF_ACCEPTANCE)
  private OffsetDateTime dateOfAcceptance;

  public static final String SERIALIZED_NAME_DATE_OF_DELIVERY = "dateOfDelivery";
  @SerializedName(SERIALIZED_NAME_DATE_OF_DELIVERY)
  private OffsetDateTime dateOfDelivery;

  public static final String SERIALIZED_NAME_FREIGHT_TERMS = "freightTerms";
  @SerializedName(SERIALIZED_NAME_FREIGHT_TERMS)
  private String freightTerms;

  public static final String SERIALIZED_NAME_FREIGHT_AMOUNT = "freightAmount";
  @SerializedName(SERIALIZED_NAME_FREIGHT_AMOUNT)
  private Double freightAmount;

  public static final String SERIALIZED_NAME_FREIGHT_CURRENCY_ID = "freightCurrencyId";
  @SerializedName(SERIALIZED_NAME_FREIGHT_CURRENCY_ID)
  private String freightCurrencyId;

  public static final String SERIALIZED_NAME_TOTAL_GROSS_WEIGHT_KG = "totalGrossWeightKg";
  @SerializedName(SERIALIZED_NAME_TOTAL_GROSS_WEIGHT_KG)
  private Double totalGrossWeightKg;

  public static final String SERIALIZED_NAME_TOTAL_PACKAGES = "totalPackages";
  @SerializedName(SERIALIZED_NAME_TOTAL_PACKAGES)
  private Integer totalPackages;

  public static final String SERIALIZED_NAME_TOTAL_VOLUME_M3 = "totalVolumeM3";
  @SerializedName(SERIALIZED_NAME_TOTAL_VOLUME_M3)
  private Double totalVolumeM3;

  public static final String SERIALIZED_NAME_CUSTOMS_FORMALITIES = "customsFormalities";
  @SerializedName(SERIALIZED_NAME_CUSTOMS_FORMALITIES)
  private String customsFormalities;

  public static final String SERIALIZED_NAME_SPECIAL_INSTRUCTIONS = "specialInstructions";
  @SerializedName(SERIALIZED_NAME_SPECIAL_INSTRUCTIONS)
  private String specialInstructions;

  public static final String SERIALIZED_NAME_REMARKS = "remarks";
  @SerializedName(SERIALIZED_NAME_REMARKS)
  private String remarks;

  public static final String SERIALIZED_NAME_SENDER_SIGNED_DATE = "senderSignedDate";
  @SerializedName(SERIALIZED_NAME_SENDER_SIGNED_DATE)
  private OffsetDateTime senderSignedDate;

  public static final String SERIALIZED_NAME_CARRIER_SIGNED_DATE = "carrierSignedDate";
  @SerializedName(SERIALIZED_NAME_CARRIER_SIGNED_DATE)
  private OffsetDateTime carrierSignedDate;

  public static final String SERIALIZED_NAME_SHIPMENT_ID = "shipmentId";
  @SerializedName(SERIALIZED_NAME_SHIPMENT_ID)
  private String shipmentId;

  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  private String tenantId;

  public static final String SERIALIZED_NAME_ENROLLMENT_ID = "enrollmentId";
  @SerializedName(SERIALIZED_NAME_ENROLLMENT_ID)
  private String enrollmentId;

  public static final String SERIALIZED_NAME_LINES = "lines";
  @SerializedName(SERIALIZED_NAME_LINES)
  private List<WaybillLineDto> lines;

  public RailWaybillDto() {
  }

  public RailWaybillDto id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public RailWaybillDto timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nullable
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public RailWaybillDto documentNumber(String documentNumber) {
    this.documentNumber = documentNumber;
    return this;
  }

  /**
   * Get documentNumber
   * @return documentNumber
   */
  @javax.annotation.Nullable
  public String getDocumentNumber() {
    return documentNumber;
  }

  public void setDocumentNumber(String documentNumber) {
    this.documentNumber = documentNumber;
  }


  public RailWaybillDto status(String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  public RailWaybillDto shipperContactId(String shipperContactId) {
    this.shipperContactId = shipperContactId;
    return this;
  }

  /**
   * Get shipperContactId
   * @return shipperContactId
   */
  @javax.annotation.Nullable
  public String getShipperContactId() {
    return shipperContactId;
  }

  public void setShipperContactId(String shipperContactId) {
    this.shipperContactId = shipperContactId;
  }


  public RailWaybillDto consigneeContactId(String consigneeContactId) {
    this.consigneeContactId = consigneeContactId;
    return this;
  }

  /**
   * Get consigneeContactId
   * @return consigneeContactId
   */
  @javax.annotation.Nullable
  public String getConsigneeContactId() {
    return consigneeContactId;
  }

  public void setConsigneeContactId(String consigneeContactId) {
    this.consigneeContactId = consigneeContactId;
  }


  public RailWaybillDto carrierId(String carrierId) {
    this.carrierId = carrierId;
    return this;
  }

  /**
   * Get carrierId
   * @return carrierId
   */
  @javax.annotation.Nullable
  public String getCarrierId() {
    return carrierId;
  }

  public void setCarrierId(String carrierId) {
    this.carrierId = carrierId;
  }


  public RailWaybillDto railOperatorName(String railOperatorName) {
    this.railOperatorName = railOperatorName;
    return this;
  }

  /**
   * Get railOperatorName
   * @return railOperatorName
   */
  @javax.annotation.Nullable
  public String getRailOperatorName() {
    return railOperatorName;
  }

  public void setRailOperatorName(String railOperatorName) {
    this.railOperatorName = railOperatorName;
  }


  public RailWaybillDto stationOfDeparture(String stationOfDeparture) {
    this.stationOfDeparture = stationOfDeparture;
    return this;
  }

  /**
   * Get stationOfDeparture
   * @return stationOfDeparture
   */
  @javax.annotation.Nullable
  public String getStationOfDeparture() {
    return stationOfDeparture;
  }

  public void setStationOfDeparture(String stationOfDeparture) {
    this.stationOfDeparture = stationOfDeparture;
  }


  public RailWaybillDto stationOfDepartureCode(String stationOfDepartureCode) {
    this.stationOfDepartureCode = stationOfDepartureCode;
    return this;
  }

  /**
   * Get stationOfDepartureCode
   * @return stationOfDepartureCode
   */
  @javax.annotation.Nullable
  public String getStationOfDepartureCode() {
    return stationOfDepartureCode;
  }

  public void setStationOfDepartureCode(String stationOfDepartureCode) {
    this.stationOfDepartureCode = stationOfDepartureCode;
  }


  public RailWaybillDto stationOfDestination(String stationOfDestination) {
    this.stationOfDestination = stationOfDestination;
    return this;
  }

  /**
   * Get stationOfDestination
   * @return stationOfDestination
   */
  @javax.annotation.Nullable
  public String getStationOfDestination() {
    return stationOfDestination;
  }

  public void setStationOfDestination(String stationOfDestination) {
    this.stationOfDestination = stationOfDestination;
  }


  public RailWaybillDto stationOfDestinationCode(String stationOfDestinationCode) {
    this.stationOfDestinationCode = stationOfDestinationCode;
    return this;
  }

  /**
   * Get stationOfDestinationCode
   * @return stationOfDestinationCode
   */
  @javax.annotation.Nullable
  public String getStationOfDestinationCode() {
    return stationOfDestinationCode;
  }

  public void setStationOfDestinationCode(String stationOfDestinationCode) {
    this.stationOfDestinationCode = stationOfDestinationCode;
  }


  public RailWaybillDto prescribedRoute(String prescribedRoute) {
    this.prescribedRoute = prescribedRoute;
    return this;
  }

  /**
   * Get prescribedRoute
   * @return prescribedRoute
   */
  @javax.annotation.Nullable
  public String getPrescribedRoute() {
    return prescribedRoute;
  }

  public void setPrescribedRoute(String prescribedRoute) {
    this.prescribedRoute = prescribedRoute;
  }


  public RailWaybillDto wagonNumbers(String wagonNumbers) {
    this.wagonNumbers = wagonNumbers;
    return this;
  }

  /**
   * Get wagonNumbers
   * @return wagonNumbers
   */
  @javax.annotation.Nullable
  public String getWagonNumbers() {
    return wagonNumbers;
  }

  public void setWagonNumbers(String wagonNumbers) {
    this.wagonNumbers = wagonNumbers;
  }


  public RailWaybillDto dateOfAcceptance(OffsetDateTime dateOfAcceptance) {
    this.dateOfAcceptance = dateOfAcceptance;
    return this;
  }

  /**
   * Get dateOfAcceptance
   * @return dateOfAcceptance
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDateOfAcceptance() {
    return dateOfAcceptance;
  }

  public void setDateOfAcceptance(OffsetDateTime dateOfAcceptance) {
    this.dateOfAcceptance = dateOfAcceptance;
  }


  public RailWaybillDto dateOfDelivery(OffsetDateTime dateOfDelivery) {
    this.dateOfDelivery = dateOfDelivery;
    return this;
  }

  /**
   * Get dateOfDelivery
   * @return dateOfDelivery
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDateOfDelivery() {
    return dateOfDelivery;
  }

  public void setDateOfDelivery(OffsetDateTime dateOfDelivery) {
    this.dateOfDelivery = dateOfDelivery;
  }


  public RailWaybillDto freightTerms(String freightTerms) {
    this.freightTerms = freightTerms;
    return this;
  }

  /**
   * Get freightTerms
   * @return freightTerms
   */
  @javax.annotation.Nullable
  public String getFreightTerms() {
    return freightTerms;
  }

  public void setFreightTerms(String freightTerms) {
    this.freightTerms = freightTerms;
  }


  public RailWaybillDto freightAmount(Double freightAmount) {
    this.freightAmount = freightAmount;
    return this;
  }

  /**
   * Get freightAmount
   * @return freightAmount
   */
  @javax.annotation.Nullable
  public Double getFreightAmount() {
    return freightAmount;
  }

  public void setFreightAmount(Double freightAmount) {
    this.freightAmount = freightAmount;
  }


  public RailWaybillDto freightCurrencyId(String freightCurrencyId) {
    this.freightCurrencyId = freightCurrencyId;
    return this;
  }

  /**
   * Get freightCurrencyId
   * @return freightCurrencyId
   */
  @javax.annotation.Nullable
  public String getFreightCurrencyId() {
    return freightCurrencyId;
  }

  public void setFreightCurrencyId(String freightCurrencyId) {
    this.freightCurrencyId = freightCurrencyId;
  }


  public RailWaybillDto totalGrossWeightKg(Double totalGrossWeightKg) {
    this.totalGrossWeightKg = totalGrossWeightKg;
    return this;
  }

  /**
   * Get totalGrossWeightKg
   * @return totalGrossWeightKg
   */
  @javax.annotation.Nullable
  public Double getTotalGrossWeightKg() {
    return totalGrossWeightKg;
  }

  public void setTotalGrossWeightKg(Double totalGrossWeightKg) {
    this.totalGrossWeightKg = totalGrossWeightKg;
  }


  public RailWaybillDto totalPackages(Integer totalPackages) {
    this.totalPackages = totalPackages;
    return this;
  }

  /**
   * Get totalPackages
   * @return totalPackages
   */
  @javax.annotation.Nullable
  public Integer getTotalPackages() {
    return totalPackages;
  }

  public void setTotalPackages(Integer totalPackages) {
    this.totalPackages = totalPackages;
  }


  public RailWaybillDto totalVolumeM3(Double totalVolumeM3) {
    this.totalVolumeM3 = totalVolumeM3;
    return this;
  }

  /**
   * Get totalVolumeM3
   * @return totalVolumeM3
   */
  @javax.annotation.Nullable
  public Double getTotalVolumeM3() {
    return totalVolumeM3;
  }

  public void setTotalVolumeM3(Double totalVolumeM3) {
    this.totalVolumeM3 = totalVolumeM3;
  }


  public RailWaybillDto customsFormalities(String customsFormalities) {
    this.customsFormalities = customsFormalities;
    return this;
  }

  /**
   * Get customsFormalities
   * @return customsFormalities
   */
  @javax.annotation.Nullable
  public String getCustomsFormalities() {
    return customsFormalities;
  }

  public void setCustomsFormalities(String customsFormalities) {
    this.customsFormalities = customsFormalities;
  }


  public RailWaybillDto specialInstructions(String specialInstructions) {
    this.specialInstructions = specialInstructions;
    return this;
  }

  /**
   * Get specialInstructions
   * @return specialInstructions
   */
  @javax.annotation.Nullable
  public String getSpecialInstructions() {
    return specialInstructions;
  }

  public void setSpecialInstructions(String specialInstructions) {
    this.specialInstructions = specialInstructions;
  }


  public RailWaybillDto remarks(String remarks) {
    this.remarks = remarks;
    return this;
  }

  /**
   * Get remarks
   * @return remarks
   */
  @javax.annotation.Nullable
  public String getRemarks() {
    return remarks;
  }

  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }


  public RailWaybillDto senderSignedDate(OffsetDateTime senderSignedDate) {
    this.senderSignedDate = senderSignedDate;
    return this;
  }

  /**
   * Get senderSignedDate
   * @return senderSignedDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getSenderSignedDate() {
    return senderSignedDate;
  }

  public void setSenderSignedDate(OffsetDateTime senderSignedDate) {
    this.senderSignedDate = senderSignedDate;
  }


  public RailWaybillDto carrierSignedDate(OffsetDateTime carrierSignedDate) {
    this.carrierSignedDate = carrierSignedDate;
    return this;
  }

  /**
   * Get carrierSignedDate
   * @return carrierSignedDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCarrierSignedDate() {
    return carrierSignedDate;
  }

  public void setCarrierSignedDate(OffsetDateTime carrierSignedDate) {
    this.carrierSignedDate = carrierSignedDate;
  }


  public RailWaybillDto shipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
    return this;
  }

  /**
   * Get shipmentId
   * @return shipmentId
   */
  @javax.annotation.Nullable
  public String getShipmentId() {
    return shipmentId;
  }

  public void setShipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
  }


  public RailWaybillDto tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Get tenantId
   * @return tenantId
   */
  @javax.annotation.Nullable
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }


  public RailWaybillDto enrollmentId(String enrollmentId) {
    this.enrollmentId = enrollmentId;
    return this;
  }

  /**
   * Get enrollmentId
   * @return enrollmentId
   */
  @javax.annotation.Nullable
  public String getEnrollmentId() {
    return enrollmentId;
  }

  public void setEnrollmentId(String enrollmentId) {
    this.enrollmentId = enrollmentId;
  }


  public RailWaybillDto lines(List<WaybillLineDto> lines) {
    this.lines = lines;
    return this;
  }

  public RailWaybillDto addLinesItem(WaybillLineDto linesItem) {
    if (this.lines == null) {
      this.lines = new ArrayList<>();
    }
    this.lines.add(linesItem);
    return this;
  }

  /**
   * Get lines
   * @return lines
   */
  @javax.annotation.Nullable
  public List<WaybillLineDto> getLines() {
    return lines;
  }

  public void setLines(List<WaybillLineDto> lines) {
    this.lines = lines;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RailWaybillDto railWaybillDto = (RailWaybillDto) o;
    return Objects.equals(this.id, railWaybillDto.id) &&
        Objects.equals(this.timestamp, railWaybillDto.timestamp) &&
        Objects.equals(this.documentNumber, railWaybillDto.documentNumber) &&
        Objects.equals(this.status, railWaybillDto.status) &&
        Objects.equals(this.shipperContactId, railWaybillDto.shipperContactId) &&
        Objects.equals(this.consigneeContactId, railWaybillDto.consigneeContactId) &&
        Objects.equals(this.carrierId, railWaybillDto.carrierId) &&
        Objects.equals(this.railOperatorName, railWaybillDto.railOperatorName) &&
        Objects.equals(this.stationOfDeparture, railWaybillDto.stationOfDeparture) &&
        Objects.equals(this.stationOfDepartureCode, railWaybillDto.stationOfDepartureCode) &&
        Objects.equals(this.stationOfDestination, railWaybillDto.stationOfDestination) &&
        Objects.equals(this.stationOfDestinationCode, railWaybillDto.stationOfDestinationCode) &&
        Objects.equals(this.prescribedRoute, railWaybillDto.prescribedRoute) &&
        Objects.equals(this.wagonNumbers, railWaybillDto.wagonNumbers) &&
        Objects.equals(this.dateOfAcceptance, railWaybillDto.dateOfAcceptance) &&
        Objects.equals(this.dateOfDelivery, railWaybillDto.dateOfDelivery) &&
        Objects.equals(this.freightTerms, railWaybillDto.freightTerms) &&
        Objects.equals(this.freightAmount, railWaybillDto.freightAmount) &&
        Objects.equals(this.freightCurrencyId, railWaybillDto.freightCurrencyId) &&
        Objects.equals(this.totalGrossWeightKg, railWaybillDto.totalGrossWeightKg) &&
        Objects.equals(this.totalPackages, railWaybillDto.totalPackages) &&
        Objects.equals(this.totalVolumeM3, railWaybillDto.totalVolumeM3) &&
        Objects.equals(this.customsFormalities, railWaybillDto.customsFormalities) &&
        Objects.equals(this.specialInstructions, railWaybillDto.specialInstructions) &&
        Objects.equals(this.remarks, railWaybillDto.remarks) &&
        Objects.equals(this.senderSignedDate, railWaybillDto.senderSignedDate) &&
        Objects.equals(this.carrierSignedDate, railWaybillDto.carrierSignedDate) &&
        Objects.equals(this.shipmentId, railWaybillDto.shipmentId) &&
        Objects.equals(this.tenantId, railWaybillDto.tenantId) &&
        Objects.equals(this.enrollmentId, railWaybillDto.enrollmentId) &&
        Objects.equals(this.lines, railWaybillDto.lines);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, timestamp, documentNumber, status, shipperContactId, consigneeContactId, carrierId, railOperatorName, stationOfDeparture, stationOfDepartureCode, stationOfDestination, stationOfDestinationCode, prescribedRoute, wagonNumbers, dateOfAcceptance, dateOfDelivery, freightTerms, freightAmount, freightCurrencyId, totalGrossWeightKg, totalPackages, totalVolumeM3, customsFormalities, specialInstructions, remarks, senderSignedDate, carrierSignedDate, shipmentId, tenantId, enrollmentId, lines);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RailWaybillDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    documentNumber: ").append(toIndentedString(documentNumber)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    shipperContactId: ").append(toIndentedString(shipperContactId)).append("\n");
    sb.append("    consigneeContactId: ").append(toIndentedString(consigneeContactId)).append("\n");
    sb.append("    carrierId: ").append(toIndentedString(carrierId)).append("\n");
    sb.append("    railOperatorName: ").append(toIndentedString(railOperatorName)).append("\n");
    sb.append("    stationOfDeparture: ").append(toIndentedString(stationOfDeparture)).append("\n");
    sb.append("    stationOfDepartureCode: ").append(toIndentedString(stationOfDepartureCode)).append("\n");
    sb.append("    stationOfDestination: ").append(toIndentedString(stationOfDestination)).append("\n");
    sb.append("    stationOfDestinationCode: ").append(toIndentedString(stationOfDestinationCode)).append("\n");
    sb.append("    prescribedRoute: ").append(toIndentedString(prescribedRoute)).append("\n");
    sb.append("    wagonNumbers: ").append(toIndentedString(wagonNumbers)).append("\n");
    sb.append("    dateOfAcceptance: ").append(toIndentedString(dateOfAcceptance)).append("\n");
    sb.append("    dateOfDelivery: ").append(toIndentedString(dateOfDelivery)).append("\n");
    sb.append("    freightTerms: ").append(toIndentedString(freightTerms)).append("\n");
    sb.append("    freightAmount: ").append(toIndentedString(freightAmount)).append("\n");
    sb.append("    freightCurrencyId: ").append(toIndentedString(freightCurrencyId)).append("\n");
    sb.append("    totalGrossWeightKg: ").append(toIndentedString(totalGrossWeightKg)).append("\n");
    sb.append("    totalPackages: ").append(toIndentedString(totalPackages)).append("\n");
    sb.append("    totalVolumeM3: ").append(toIndentedString(totalVolumeM3)).append("\n");
    sb.append("    customsFormalities: ").append(toIndentedString(customsFormalities)).append("\n");
    sb.append("    specialInstructions: ").append(toIndentedString(specialInstructions)).append("\n");
    sb.append("    remarks: ").append(toIndentedString(remarks)).append("\n");
    sb.append("    senderSignedDate: ").append(toIndentedString(senderSignedDate)).append("\n");
    sb.append("    carrierSignedDate: ").append(toIndentedString(carrierSignedDate)).append("\n");
    sb.append("    shipmentId: ").append(toIndentedString(shipmentId)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    enrollmentId: ").append(toIndentedString(enrollmentId)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("timestamp");
    openapiFields.add("documentNumber");
    openapiFields.add("status");
    openapiFields.add("shipperContactId");
    openapiFields.add("consigneeContactId");
    openapiFields.add("carrierId");
    openapiFields.add("railOperatorName");
    openapiFields.add("stationOfDeparture");
    openapiFields.add("stationOfDepartureCode");
    openapiFields.add("stationOfDestination");
    openapiFields.add("stationOfDestinationCode");
    openapiFields.add("prescribedRoute");
    openapiFields.add("wagonNumbers");
    openapiFields.add("dateOfAcceptance");
    openapiFields.add("dateOfDelivery");
    openapiFields.add("freightTerms");
    openapiFields.add("freightAmount");
    openapiFields.add("freightCurrencyId");
    openapiFields.add("totalGrossWeightKg");
    openapiFields.add("totalPackages");
    openapiFields.add("totalVolumeM3");
    openapiFields.add("customsFormalities");
    openapiFields.add("specialInstructions");
    openapiFields.add("remarks");
    openapiFields.add("senderSignedDate");
    openapiFields.add("carrierSignedDate");
    openapiFields.add("shipmentId");
    openapiFields.add("tenantId");
    openapiFields.add("enrollmentId");
    openapiFields.add("lines");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RailWaybillDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RailWaybillDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RailWaybillDto is not found in the empty JSON string", RailWaybillDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RailWaybillDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RailWaybillDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("documentNumber") != null && !jsonObj.get("documentNumber").isJsonNull()) && !jsonObj.get("documentNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `documentNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("documentNumber").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("shipperContactId") != null && !jsonObj.get("shipperContactId").isJsonNull()) && !jsonObj.get("shipperContactId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shipperContactId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shipperContactId").toString()));
      }
      if ((jsonObj.get("consigneeContactId") != null && !jsonObj.get("consigneeContactId").isJsonNull()) && !jsonObj.get("consigneeContactId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `consigneeContactId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("consigneeContactId").toString()));
      }
      if ((jsonObj.get("carrierId") != null && !jsonObj.get("carrierId").isJsonNull()) && !jsonObj.get("carrierId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `carrierId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("carrierId").toString()));
      }
      if ((jsonObj.get("railOperatorName") != null && !jsonObj.get("railOperatorName").isJsonNull()) && !jsonObj.get("railOperatorName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `railOperatorName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("railOperatorName").toString()));
      }
      if ((jsonObj.get("stationOfDeparture") != null && !jsonObj.get("stationOfDeparture").isJsonNull()) && !jsonObj.get("stationOfDeparture").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stationOfDeparture` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stationOfDeparture").toString()));
      }
      if ((jsonObj.get("stationOfDepartureCode") != null && !jsonObj.get("stationOfDepartureCode").isJsonNull()) && !jsonObj.get("stationOfDepartureCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stationOfDepartureCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stationOfDepartureCode").toString()));
      }
      if ((jsonObj.get("stationOfDestination") != null && !jsonObj.get("stationOfDestination").isJsonNull()) && !jsonObj.get("stationOfDestination").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stationOfDestination` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stationOfDestination").toString()));
      }
      if ((jsonObj.get("stationOfDestinationCode") != null && !jsonObj.get("stationOfDestinationCode").isJsonNull()) && !jsonObj.get("stationOfDestinationCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stationOfDestinationCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stationOfDestinationCode").toString()));
      }
      if ((jsonObj.get("prescribedRoute") != null && !jsonObj.get("prescribedRoute").isJsonNull()) && !jsonObj.get("prescribedRoute").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `prescribedRoute` to be a primitive type in the JSON string but got `%s`", jsonObj.get("prescribedRoute").toString()));
      }
      if ((jsonObj.get("wagonNumbers") != null && !jsonObj.get("wagonNumbers").isJsonNull()) && !jsonObj.get("wagonNumbers").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `wagonNumbers` to be a primitive type in the JSON string but got `%s`", jsonObj.get("wagonNumbers").toString()));
      }
      if ((jsonObj.get("freightTerms") != null && !jsonObj.get("freightTerms").isJsonNull()) && !jsonObj.get("freightTerms").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `freightTerms` to be a primitive type in the JSON string but got `%s`", jsonObj.get("freightTerms").toString()));
      }
      if ((jsonObj.get("freightCurrencyId") != null && !jsonObj.get("freightCurrencyId").isJsonNull()) && !jsonObj.get("freightCurrencyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `freightCurrencyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("freightCurrencyId").toString()));
      }
      if ((jsonObj.get("customsFormalities") != null && !jsonObj.get("customsFormalities").isJsonNull()) && !jsonObj.get("customsFormalities").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customsFormalities` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customsFormalities").toString()));
      }
      if ((jsonObj.get("specialInstructions") != null && !jsonObj.get("specialInstructions").isJsonNull()) && !jsonObj.get("specialInstructions").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `specialInstructions` to be a primitive type in the JSON string but got `%s`", jsonObj.get("specialInstructions").toString()));
      }
      if ((jsonObj.get("remarks") != null && !jsonObj.get("remarks").isJsonNull()) && !jsonObj.get("remarks").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `remarks` to be a primitive type in the JSON string but got `%s`", jsonObj.get("remarks").toString()));
      }
      if ((jsonObj.get("shipmentId") != null && !jsonObj.get("shipmentId").isJsonNull()) && !jsonObj.get("shipmentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shipmentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shipmentId").toString()));
      }
      if ((jsonObj.get("tenantId") != null && !jsonObj.get("tenantId").isJsonNull()) && !jsonObj.get("tenantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantId").toString()));
      }
      if ((jsonObj.get("enrollmentId") != null && !jsonObj.get("enrollmentId").isJsonNull()) && !jsonObj.get("enrollmentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `enrollmentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("enrollmentId").toString()));
      }
      if (jsonObj.get("lines") != null && !jsonObj.get("lines").isJsonNull()) {
        JsonArray jsonArraylines = jsonObj.getAsJsonArray("lines");
        if (jsonArraylines != null) {
          // ensure the json data is an array
          if (!jsonObj.get("lines").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `lines` to be an array in the JSON string but got `%s`", jsonObj.get("lines").toString()));
          }

          // validate the optional field `lines` (array)
          for (int i = 0; i < jsonArraylines.size(); i++) {
            WaybillLineDto.validateJsonElement(jsonArraylines.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RailWaybillDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RailWaybillDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RailWaybillDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RailWaybillDto.class));

       return (TypeAdapter<T>) new TypeAdapter<RailWaybillDto>() {
           @Override
           public void write(JsonWriter out, RailWaybillDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RailWaybillDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RailWaybillDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RailWaybillDto
   * @throws IOException if the JSON string is invalid with respect to RailWaybillDto
   */
  public static RailWaybillDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RailWaybillDto.class);
  }

  /**
   * Convert an instance of RailWaybillDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

