/*
 * ContentService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ContactDto;
import org.openapitools.client.model.TenantDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CrmContext
 */
public class CrmContextTest {
    private final CrmContext model = new CrmContext();

    /**
     * Model tests for CrmContext
     */
    @Test
    public void testCrmContext() {
        // TODO: test CrmContext
    }

    /**
     * Test the property 'ownerTenantId'
     */
    @Test
    public void ownerTenantIdTest() {
        // TODO: test ownerTenantId
    }

    /**
     * Test the property 'ownerTenant'
     */
    @Test
    public void ownerTenantTest() {
        // TODO: test ownerTenant
    }

    /**
     * Test the property 'userContactId'
     */
    @Test
    public void userContactIdTest() {
        // TODO: test userContactId
    }

    /**
     * Test the property 'tenantContactId'
     */
    @Test
    public void tenantContactIdTest() {
        // TODO: test tenantContactId
    }

    /**
     * Test the property 'userContact'
     */
    @Test
    public void userContactTest() {
        // TODO: test userContact
    }

    /**
     * Test the property 'tenantContact'
     */
    @Test
    public void tenantContactTest() {
        // TODO: test tenantContact
    }

}
