/*
 * ContentService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5401
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ApplyQueryOption;
import org.openapitools.client.model.ComputeQueryOption;
import org.openapitools.client.model.CountQueryOption;
import org.openapitools.client.model.FilterQueryOption;
import org.openapitools.client.model.HttpRequest;
import org.openapitools.client.model.ODataQueryContext;
import org.openapitools.client.model.ODataRawQueryOptions;
import org.openapitools.client.model.OrderByQueryOption;
import org.openapitools.client.model.SearchQueryOption;
import org.openapitools.client.model.SelectExpandQueryOption;
import org.openapitools.client.model.SkipQueryOption;
import org.openapitools.client.model.SkipTokenQueryOption;
import org.openapitools.client.model.TopQueryOption;
import org.openapitools.client.model.WebsiteThemeDtoETag;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebsiteThemeDtoODataQueryOptions
 */
public class WebsiteThemeDtoODataQueryOptionsTest {
    private final WebsiteThemeDtoODataQueryOptions model = new WebsiteThemeDtoODataQueryOptions();

    /**
     * Model tests for WebsiteThemeDtoODataQueryOptions
     */
    @Test
    public void testWebsiteThemeDtoODataQueryOptions() {
        // TODO: test WebsiteThemeDtoODataQueryOptions
    }

    /**
     * Test the property 'request'
     */
    @Test
    public void requestTest() {
        // TODO: test request
    }

    /**
     * Test the property 'context'
     */
    @Test
    public void contextTest() {
        // TODO: test context
    }

    /**
     * Test the property 'rawValues'
     */
    @Test
    public void rawValuesTest() {
        // TODO: test rawValues
    }

    /**
     * Test the property 'selectExpand'
     */
    @Test
    public void selectExpandTest() {
        // TODO: test selectExpand
    }

    /**
     * Test the property 'apply'
     */
    @Test
    public void applyTest() {
        // TODO: test apply
    }

    /**
     * Test the property 'compute'
     */
    @Test
    public void computeTest() {
        // TODO: test compute
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

    /**
     * Test the property 'search'
     */
    @Test
    public void searchTest() {
        // TODO: test search
    }

    /**
     * Test the property 'orderBy'
     */
    @Test
    public void orderByTest() {
        // TODO: test orderBy
    }

    /**
     * Test the property 'skip'
     */
    @Test
    public void skipTest() {
        // TODO: test skip
    }

    /**
     * Test the property 'skipToken'
     */
    @Test
    public void skipTokenTest() {
        // TODO: test skipToken
    }

    /**
     * Test the property 'top'
     */
    @Test
    public void topTest() {
        // TODO: test top
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'validator'
     */
    @Test
    public void validatorTest() {
        // TODO: test validator
    }

    /**
     * Test the property 'ifMatch'
     */
    @Test
    public void ifMatchTest() {
        // TODO: test ifMatch
    }

    /**
     * Test the property 'ifNoneMatch'
     */
    @Test
    public void ifNoneMatchTest() {
        // TODO: test ifNoneMatch
    }

}
