/*
 * OrdersService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.OrderLineCreateDto;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * OrderCreateDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-19T21:26:21.041850500-05:00[America/Bogota]", comments = "Generator version: 7.9.0")
public class OrderCreateDto {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  private OffsetDateTime timestamp;

  public static final String SERIALIZED_NAME_CLOSED = "closed";
  @SerializedName(SERIALIZED_NAME_CLOSED)
  private Boolean closed;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_PRICE_LIST_ID = "priceListId";
  @SerializedName(SERIALIZED_NAME_PRICE_LIST_ID)
  private String priceListId;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_INDIVIDUAL_ID = "individualId";
  @SerializedName(SERIALIZED_NAME_INDIVIDUAL_ID)
  private String individualId;

  public static final String SERIALIZED_NAME_PAYMENT_TERM_ID = "paymentTermId";
  @SerializedName(SERIALIZED_NAME_PAYMENT_TERM_ID)
  private String paymentTermId;

  public static final String SERIALIZED_NAME_ORGANIZATION_ID = "organizationId";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_ID)
  private String organizationId;

  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "lastName";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private String lastName;

  public static final String SERIALIZED_NAME_COMPANY_NAME = "companyName";
  @SerializedName(SERIALIZED_NAME_COMPANY_NAME)
  private String companyName;

  public static final String SERIALIZED_NAME_BILLING_EMAIL = "billingEmail";
  @SerializedName(SERIALIZED_NAME_BILLING_EMAIL)
  private String billingEmail;

  public static final String SERIALIZED_NAME_ADDRESS_LINE1 = "addressLine1";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE1)
  private String addressLine1;

  public static final String SERIALIZED_NAME_ADDRESS_LINE2 = "addressLine2";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE2)
  private String addressLine2;

  public static final String SERIALIZED_NAME_POSTAL_CODE = "postalCode";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE)
  private String postalCode;

  public static final String SERIALIZED_NAME_COUNTRY_ID = "countryId";
  @SerializedName(SERIALIZED_NAME_COUNTRY_ID)
  private String countryId;

  public static final String SERIALIZED_NAME_STATE_ID = "stateId";
  @SerializedName(SERIALIZED_NAME_STATE_ID)
  private String stateId;

  public static final String SERIALIZED_NAME_CITY_ID = "cityId";
  @SerializedName(SERIALIZED_NAME_CITY_ID)
  private String cityId;

  public static final String SERIALIZED_NAME_FOREX_RATE = "forexRate";
  @SerializedName(SERIALIZED_NAME_FOREX_RATE)
  private Double forexRate;

  public static final String SERIALIZED_NAME_CURRENCY_ID = "currencyId";
  @SerializedName(SERIALIZED_NAME_CURRENCY_ID)
  private String currencyId;

  public static final String SERIALIZED_NAME_TOTAL_DETAIL = "totalDetail";
  @SerializedName(SERIALIZED_NAME_TOTAL_DETAIL)
  private Double totalDetail;

  public static final String SERIALIZED_NAME_TOTAL_DETAIL_CURRENCY_ID = "totalDetailCurrencyId";
  @SerializedName(SERIALIZED_NAME_TOTAL_DETAIL_CURRENCY_ID)
  private String totalDetailCurrencyId;

  public static final String SERIALIZED_NAME_TOTAL_PROFIT = "totalProfit";
  @SerializedName(SERIALIZED_NAME_TOTAL_PROFIT)
  private Double totalProfit;

  public static final String SERIALIZED_NAME_TOTAL_PROFIT_CURRENCY_ID = "totalProfitCurrencyId";
  @SerializedName(SERIALIZED_NAME_TOTAL_PROFIT_CURRENCY_ID)
  private String totalProfitCurrencyId;

  public static final String SERIALIZED_NAME_TOTAL_DISCOUNTS = "totalDiscounts";
  @SerializedName(SERIALIZED_NAME_TOTAL_DISCOUNTS)
  private Double totalDiscounts;

  public static final String SERIALIZED_NAME_TOTAL_DISCOUNTS_CURRENCY_ID = "totalDiscountsCurrencyId";
  @SerializedName(SERIALIZED_NAME_TOTAL_DISCOUNTS_CURRENCY_ID)
  private String totalDiscountsCurrencyId;

  public static final String SERIALIZED_NAME_TOTAL_SURCHARGES = "totalSurcharges";
  @SerializedName(SERIALIZED_NAME_TOTAL_SURCHARGES)
  private Double totalSurcharges;

  public static final String SERIALIZED_NAME_TOTAL_SURCHARGES_CURRENCY_ID = "totalSurchargesCurrencyId";
  @SerializedName(SERIALIZED_NAME_TOTAL_SURCHARGES_CURRENCY_ID)
  private String totalSurchargesCurrencyId;

  public static final String SERIALIZED_NAME_TOTAL_SHIPPING_COST = "totalShippingCost";
  @SerializedName(SERIALIZED_NAME_TOTAL_SHIPPING_COST)
  private Double totalShippingCost;

  public static final String SERIALIZED_NAME_TOTAL_SHIPPING_COST_CURRENCY_ID = "totalShippingCostCurrencyId";
  @SerializedName(SERIALIZED_NAME_TOTAL_SHIPPING_COST_CURRENCY_ID)
  private String totalShippingCostCurrencyId;

  public static final String SERIALIZED_NAME_TOTAL_SHIPPING_TAX = "totalShippingTax";
  @SerializedName(SERIALIZED_NAME_TOTAL_SHIPPING_TAX)
  private Double totalShippingTax;

  public static final String SERIALIZED_NAME_TOTAL_SHIPPING_TAX_CURRENCY_ID = "totalShippingTaxCurrencyId";
  @SerializedName(SERIALIZED_NAME_TOTAL_SHIPPING_TAX_CURRENCY_ID)
  private String totalShippingTaxCurrencyId;

  public static final String SERIALIZED_NAME_TOTAL_WITHHELD_TAX = "totalWithheldTax";
  @SerializedName(SERIALIZED_NAME_TOTAL_WITHHELD_TAX)
  private Double totalWithheldTax;

  public static final String SERIALIZED_NAME_TOTAL_WITHHELD_TAX_CURRENCY_ID = "totalWithheldTaxCurrencyId";
  @SerializedName(SERIALIZED_NAME_TOTAL_WITHHELD_TAX_CURRENCY_ID)
  private String totalWithheldTaxCurrencyId;

  public static final String SERIALIZED_NAME_TOTAL_TAX_BASE = "totalTaxBase";
  @SerializedName(SERIALIZED_NAME_TOTAL_TAX_BASE)
  private Double totalTaxBase;

  public static final String SERIALIZED_NAME_TOTAL_TAX_BASE_CURRENCY_ID = "totalTaxBaseCurrencyId";
  @SerializedName(SERIALIZED_NAME_TOTAL_TAX_BASE_CURRENCY_ID)
  private String totalTaxBaseCurrencyId;

  public static final String SERIALIZED_NAME_TOTAL_TAXES = "totalTaxes";
  @SerializedName(SERIALIZED_NAME_TOTAL_TAXES)
  private Double totalTaxes;

  public static final String SERIALIZED_NAME_TOTAL_TAXES_CURRENCY_ID = "totalTaxesCurrencyId";
  @SerializedName(SERIALIZED_NAME_TOTAL_TAXES_CURRENCY_ID)
  private String totalTaxesCurrencyId;

  public static final String SERIALIZED_NAME_TOTAL_GLOBAL_SURCHARGES = "totalGlobalSurcharges";
  @SerializedName(SERIALIZED_NAME_TOTAL_GLOBAL_SURCHARGES)
  private Double totalGlobalSurcharges;

  public static final String SERIALIZED_NAME_TOTAL_GLOBAL_SURCHARGES_CURRENCY_ID = "totalGlobalSurchargesCurrencyId";
  @SerializedName(SERIALIZED_NAME_TOTAL_GLOBAL_SURCHARGES_CURRENCY_ID)
  private String totalGlobalSurchargesCurrencyId;

  public static final String SERIALIZED_NAME_TOTAL_GLOBAL_DISCOUNTS = "totalGlobalDiscounts";
  @SerializedName(SERIALIZED_NAME_TOTAL_GLOBAL_DISCOUNTS)
  private Double totalGlobalDiscounts;

  public static final String SERIALIZED_NAME_TOTAL_GLOBAL_DISCOUNTS_CURRENCY_ID = "totalGlobalDiscountsCurrencyId";
  @SerializedName(SERIALIZED_NAME_TOTAL_GLOBAL_DISCOUNTS_CURRENCY_ID)
  private String totalGlobalDiscountsCurrencyId;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Double total;

  public static final String SERIALIZED_NAME_TOTAL_CURRENCY_ID = "totalCurrencyId";
  @SerializedName(SERIALIZED_NAME_TOTAL_CURRENCY_ID)
  private String totalCurrencyId;

  /**
   * Gets or Sets costCalculationMethod
   */
  @JsonAdapter(CostCalculationMethodEnum.Adapter.class)
  public enum CostCalculationMethodEnum {
    AUTOMATIC("Automatic"),
    
    CUSTOM("Custom");

    private String value;

    CostCalculationMethodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CostCalculationMethodEnum fromValue(String value) {
      for (CostCalculationMethodEnum b : CostCalculationMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CostCalculationMethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CostCalculationMethodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CostCalculationMethodEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CostCalculationMethodEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CostCalculationMethodEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_COST_CALCULATION_METHOD = "costCalculationMethod";
  @SerializedName(SERIALIZED_NAME_COST_CALCULATION_METHOD)
  private CostCalculationMethodEnum costCalculationMethod;

  /**
   * Gets or Sets taxCalculationMethod
   */
  @JsonAdapter(TaxCalculationMethodEnum.Adapter.class)
  public enum TaxCalculationMethodEnum {
    INCLUDED("Included"),
    
    EXCLUDED("Excluded");

    private String value;

    TaxCalculationMethodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TaxCalculationMethodEnum fromValue(String value) {
      for (TaxCalculationMethodEnum b : TaxCalculationMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TaxCalculationMethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TaxCalculationMethodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TaxCalculationMethodEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TaxCalculationMethodEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TaxCalculationMethodEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TAX_CALCULATION_METHOD = "taxCalculationMethod";
  @SerializedName(SERIALIZED_NAME_TAX_CALCULATION_METHOD)
  private TaxCalculationMethodEnum taxCalculationMethod;

  public static final String SERIALIZED_NAME_CART_ID = "cartId";
  @SerializedName(SERIALIZED_NAME_CART_ID)
  private String cartId;

  public static final String SERIALIZED_NAME_QUOTE_ID = "quoteId";
  @SerializedName(SERIALIZED_NAME_QUOTE_ID)
  private String quoteId;

  public static final String SERIALIZED_NAME_WALLET_ID = "walletId";
  @SerializedName(SERIALIZED_NAME_WALLET_ID)
  private String walletId;

  public static final String SERIALIZED_NAME_PARENT_ORDER_ID = "parentOrderId";
  @SerializedName(SERIALIZED_NAME_PARENT_ORDER_ID)
  private String parentOrderId;

  public static final String SERIALIZED_NAME_SHIPPING_METHOD_ID = "shippingMethodId";
  @SerializedName(SERIALIZED_NAME_SHIPPING_METHOD_ID)
  private String shippingMethodId;

  public static final String SERIALIZED_NAME_BILLING_LOCATION_ID = "billingLocationId";
  @SerializedName(SERIALIZED_NAME_BILLING_LOCATION_ID)
  private String billingLocationId;

  public static final String SERIALIZED_NAME_CUSTOMER_NOTES = "customerNotes";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_NOTES)
  private String customerNotes;

  /**
   * Gets or Sets orderStatus
   */
  @JsonAdapter(OrderStatusEnum.Adapter.class)
  public enum OrderStatusEnum {
    NEW("New"),
    
    PROCESSING("Processing"),
    
    ACCEPTED("Accepted"),
    
    DECLINED("Declined"),
    
    SHIPPED("Shipped"),
    
    DELIVERED("Delivered"),
    
    ON_HOLD("OnHold"),
    
    FAILED("Failed"),
    
    FULFILLED("Fulfilled"),
    
    CANCELLED("Cancelled");

    private String value;

    OrderStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OrderStatusEnum fromValue(String value) {
      for (OrderStatusEnum b : OrderStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<OrderStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OrderStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OrderStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return OrderStatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      OrderStatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ORDER_STATUS = "orderStatus";
  @SerializedName(SERIALIZED_NAME_ORDER_STATUS)
  private OrderStatusEnum orderStatus;

  /**
   * Gets or Sets quoteStatus
   */
  @JsonAdapter(QuoteStatusEnum.Adapter.class)
  public enum QuoteStatusEnum {
    DRAFT("Draft"),
    
    NEW("New"),
    
    ACCEPTED("Accepted"),
    
    DECLINED("Declined"),
    
    EXPIRED("Expired");

    private String value;

    QuoteStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static QuoteStatusEnum fromValue(String value) {
      for (QuoteStatusEnum b : QuoteStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<QuoteStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final QuoteStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public QuoteStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return QuoteStatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      QuoteStatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_QUOTE_STATUS = "quoteStatus";
  @SerializedName(SERIALIZED_NAME_QUOTE_STATUS)
  private QuoteStatusEnum quoteStatus;

  /**
   * Gets or Sets freightTerms
   */
  @JsonAdapter(FreightTermsEnum.Adapter.class)
  public enum FreightTermsEnum {
    FOB("FOB"),
    
    NO_CHARGE("NoCharge");

    private String value;

    FreightTermsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FreightTermsEnum fromValue(String value) {
      for (FreightTermsEnum b : FreightTermsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<FreightTermsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FreightTermsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FreightTermsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return FreightTermsEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      FreightTermsEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_FREIGHT_TERMS = "freightTerms";
  @SerializedName(SERIALIZED_NAME_FREIGHT_TERMS)
  private FreightTermsEnum freightTerms;

  public static final String SERIALIZED_NAME_RECEIVER_TENANT_ID = "receiverTenantId";
  @SerializedName(SERIALIZED_NAME_RECEIVER_TENANT_ID)
  private String receiverTenantId;

  public static final String SERIALIZED_NAME_SHIPPING_LOCATION_ID = "shippingLocationId";
  @SerializedName(SERIALIZED_NAME_SHIPPING_LOCATION_ID)
  private String shippingLocationId;

  public static final String SERIALIZED_NAME_QUALIFIED_IDENTIFIER = "qualifiedIdentifier";
  @SerializedName(SERIALIZED_NAME_QUALIFIED_IDENTIFIER)
  private String qualifiedIdentifier;

  public static final String SERIALIZED_NAME_TOTAL_TAXES_IN_USD = "totalTaxesInUsd";
  @SerializedName(SERIALIZED_NAME_TOTAL_TAXES_IN_USD)
  private Double totalTaxesInUsd;

  public static final String SERIALIZED_NAME_TOTAL_DISCOUNTS_IN_USD = "totalDiscountsInUsd";
  @SerializedName(SERIALIZED_NAME_TOTAL_DISCOUNTS_IN_USD)
  private Double totalDiscountsInUsd;

  public static final String SERIALIZED_NAME_TOTAL_SURCHARGES_IN_USD = "totalSurchargesInUsd";
  @SerializedName(SERIALIZED_NAME_TOTAL_SURCHARGES_IN_USD)
  private Double totalSurchargesInUsd;

  public static final String SERIALIZED_NAME_TOTAL_SHIPPING_COST_IN_USD = "totalShippingCostInUsd";
  @SerializedName(SERIALIZED_NAME_TOTAL_SHIPPING_COST_IN_USD)
  private Double totalShippingCostInUsd;

  public static final String SERIALIZED_NAME_TOTAL_SHIPPING_TAX_IN_USD = "totalShippingTaxInUsd";
  @SerializedName(SERIALIZED_NAME_TOTAL_SHIPPING_TAX_IN_USD)
  private Double totalShippingTaxInUsd;

  public static final String SERIALIZED_NAME_TOTAL_AMOUNT_IN_USD = "totalAmountInUsd";
  @SerializedName(SERIALIZED_NAME_TOTAL_AMOUNT_IN_USD)
  private Double totalAmountInUsd;

  public static final String SERIALIZED_NAME_EFFECTIVE_TO = "effectiveTo";
  @SerializedName(SERIALIZED_NAME_EFFECTIVE_TO)
  private OffsetDateTime effectiveTo;

  public static final String SERIALIZED_NAME_EFFECTIVE_FROM = "effectiveFrom";
  @SerializedName(SERIALIZED_NAME_EFFECTIVE_FROM)
  private OffsetDateTime effectiveFrom;

  public static final String SERIALIZED_NAME_ORDER_LINES = "orderLines";
  @SerializedName(SERIALIZED_NAME_ORDER_LINES)
  private List<OrderLineCreateDto> orderLines;

  public OrderCreateDto() {
  }

  public OrderCreateDto id(UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }


  public OrderCreateDto timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nullable
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public OrderCreateDto closed(Boolean closed) {
    this.closed = closed;
    return this;
  }

  /**
   * Get closed
   * @return closed
   */
  @javax.annotation.Nullable
  public Boolean getClosed() {
    return closed;
  }

  public void setClosed(Boolean closed) {
    this.closed = closed;
  }


  public OrderCreateDto title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  public OrderCreateDto priceListId(String priceListId) {
    this.priceListId = priceListId;
    return this;
  }

  /**
   * Get priceListId
   * @return priceListId
   */
  @javax.annotation.Nullable
  public String getPriceListId() {
    return priceListId;
  }

  public void setPriceListId(String priceListId) {
    this.priceListId = priceListId;
  }


  public OrderCreateDto description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public OrderCreateDto individualId(String individualId) {
    this.individualId = individualId;
    return this;
  }

  /**
   * Get individualId
   * @return individualId
   */
  @javax.annotation.Nullable
  public String getIndividualId() {
    return individualId;
  }

  public void setIndividualId(String individualId) {
    this.individualId = individualId;
  }


  public OrderCreateDto paymentTermId(String paymentTermId) {
    this.paymentTermId = paymentTermId;
    return this;
  }

  /**
   * Get paymentTermId
   * @return paymentTermId
   */
  @javax.annotation.Nullable
  public String getPaymentTermId() {
    return paymentTermId;
  }

  public void setPaymentTermId(String paymentTermId) {
    this.paymentTermId = paymentTermId;
  }


  public OrderCreateDto organizationId(String organizationId) {
    this.organizationId = organizationId;
    return this;
  }

  /**
   * Get organizationId
   * @return organizationId
   */
  @javax.annotation.Nullable
  public String getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(String organizationId) {
    this.organizationId = organizationId;
  }


  public OrderCreateDto firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * Get firstName
   * @return firstName
   */
  @javax.annotation.Nullable
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public OrderCreateDto lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * Get lastName
   * @return lastName
   */
  @javax.annotation.Nullable
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public OrderCreateDto companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

  /**
   * Get companyName
   * @return companyName
   */
  @javax.annotation.Nullable
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }


  public OrderCreateDto billingEmail(String billingEmail) {
    this.billingEmail = billingEmail;
    return this;
  }

  /**
   * Get billingEmail
   * @return billingEmail
   */
  @javax.annotation.Nullable
  public String getBillingEmail() {
    return billingEmail;
  }

  public void setBillingEmail(String billingEmail) {
    this.billingEmail = billingEmail;
  }


  public OrderCreateDto addressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
    return this;
  }

  /**
   * Get addressLine1
   * @return addressLine1
   */
  @javax.annotation.Nullable
  public String getAddressLine1() {
    return addressLine1;
  }

  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }


  public OrderCreateDto addressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
    return this;
  }

  /**
   * Get addressLine2
   * @return addressLine2
   */
  @javax.annotation.Nullable
  public String getAddressLine2() {
    return addressLine2;
  }

  public void setAddressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
  }


  public OrderCreateDto postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

  /**
   * Get postalCode
   * @return postalCode
   */
  @javax.annotation.Nullable
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public OrderCreateDto countryId(String countryId) {
    this.countryId = countryId;
    return this;
  }

  /**
   * Get countryId
   * @return countryId
   */
  @javax.annotation.Nullable
  public String getCountryId() {
    return countryId;
  }

  public void setCountryId(String countryId) {
    this.countryId = countryId;
  }


  public OrderCreateDto stateId(String stateId) {
    this.stateId = stateId;
    return this;
  }

  /**
   * Get stateId
   * @return stateId
   */
  @javax.annotation.Nullable
  public String getStateId() {
    return stateId;
  }

  public void setStateId(String stateId) {
    this.stateId = stateId;
  }


  public OrderCreateDto cityId(String cityId) {
    this.cityId = cityId;
    return this;
  }

  /**
   * Get cityId
   * @return cityId
   */
  @javax.annotation.Nullable
  public String getCityId() {
    return cityId;
  }

  public void setCityId(String cityId) {
    this.cityId = cityId;
  }


  public OrderCreateDto forexRate(Double forexRate) {
    this.forexRate = forexRate;
    return this;
  }

  /**
   * Get forexRate
   * @return forexRate
   */
  @javax.annotation.Nullable
  public Double getForexRate() {
    return forexRate;
  }

  public void setForexRate(Double forexRate) {
    this.forexRate = forexRate;
  }


  public OrderCreateDto currencyId(String currencyId) {
    this.currencyId = currencyId;
    return this;
  }

  /**
   * Get currencyId
   * @return currencyId
   */
  @javax.annotation.Nullable
  public String getCurrencyId() {
    return currencyId;
  }

  public void setCurrencyId(String currencyId) {
    this.currencyId = currencyId;
  }


  public OrderCreateDto totalDetail(Double totalDetail) {
    this.totalDetail = totalDetail;
    return this;
  }

  /**
   * Get totalDetail
   * @return totalDetail
   */
  @javax.annotation.Nullable
  public Double getTotalDetail() {
    return totalDetail;
  }

  public void setTotalDetail(Double totalDetail) {
    this.totalDetail = totalDetail;
  }


  public OrderCreateDto totalDetailCurrencyId(String totalDetailCurrencyId) {
    this.totalDetailCurrencyId = totalDetailCurrencyId;
    return this;
  }

  /**
   * Get totalDetailCurrencyId
   * @return totalDetailCurrencyId
   */
  @javax.annotation.Nullable
  public String getTotalDetailCurrencyId() {
    return totalDetailCurrencyId;
  }

  public void setTotalDetailCurrencyId(String totalDetailCurrencyId) {
    this.totalDetailCurrencyId = totalDetailCurrencyId;
  }


  public OrderCreateDto totalProfit(Double totalProfit) {
    this.totalProfit = totalProfit;
    return this;
  }

  /**
   * Get totalProfit
   * @return totalProfit
   */
  @javax.annotation.Nullable
  public Double getTotalProfit() {
    return totalProfit;
  }

  public void setTotalProfit(Double totalProfit) {
    this.totalProfit = totalProfit;
  }


  public OrderCreateDto totalProfitCurrencyId(String totalProfitCurrencyId) {
    this.totalProfitCurrencyId = totalProfitCurrencyId;
    return this;
  }

  /**
   * Get totalProfitCurrencyId
   * @return totalProfitCurrencyId
   */
  @javax.annotation.Nullable
  public String getTotalProfitCurrencyId() {
    return totalProfitCurrencyId;
  }

  public void setTotalProfitCurrencyId(String totalProfitCurrencyId) {
    this.totalProfitCurrencyId = totalProfitCurrencyId;
  }


  public OrderCreateDto totalDiscounts(Double totalDiscounts) {
    this.totalDiscounts = totalDiscounts;
    return this;
  }

  /**
   * Get totalDiscounts
   * @return totalDiscounts
   */
  @javax.annotation.Nullable
  public Double getTotalDiscounts() {
    return totalDiscounts;
  }

  public void setTotalDiscounts(Double totalDiscounts) {
    this.totalDiscounts = totalDiscounts;
  }


  public OrderCreateDto totalDiscountsCurrencyId(String totalDiscountsCurrencyId) {
    this.totalDiscountsCurrencyId = totalDiscountsCurrencyId;
    return this;
  }

  /**
   * Get totalDiscountsCurrencyId
   * @return totalDiscountsCurrencyId
   */
  @javax.annotation.Nullable
  public String getTotalDiscountsCurrencyId() {
    return totalDiscountsCurrencyId;
  }

  public void setTotalDiscountsCurrencyId(String totalDiscountsCurrencyId) {
    this.totalDiscountsCurrencyId = totalDiscountsCurrencyId;
  }


  public OrderCreateDto totalSurcharges(Double totalSurcharges) {
    this.totalSurcharges = totalSurcharges;
    return this;
  }

  /**
   * Get totalSurcharges
   * @return totalSurcharges
   */
  @javax.annotation.Nullable
  public Double getTotalSurcharges() {
    return totalSurcharges;
  }

  public void setTotalSurcharges(Double totalSurcharges) {
    this.totalSurcharges = totalSurcharges;
  }


  public OrderCreateDto totalSurchargesCurrencyId(String totalSurchargesCurrencyId) {
    this.totalSurchargesCurrencyId = totalSurchargesCurrencyId;
    return this;
  }

  /**
   * Get totalSurchargesCurrencyId
   * @return totalSurchargesCurrencyId
   */
  @javax.annotation.Nullable
  public String getTotalSurchargesCurrencyId() {
    return totalSurchargesCurrencyId;
  }

  public void setTotalSurchargesCurrencyId(String totalSurchargesCurrencyId) {
    this.totalSurchargesCurrencyId = totalSurchargesCurrencyId;
  }


  public OrderCreateDto totalShippingCost(Double totalShippingCost) {
    this.totalShippingCost = totalShippingCost;
    return this;
  }

  /**
   * Get totalShippingCost
   * @return totalShippingCost
   */
  @javax.annotation.Nullable
  public Double getTotalShippingCost() {
    return totalShippingCost;
  }

  public void setTotalShippingCost(Double totalShippingCost) {
    this.totalShippingCost = totalShippingCost;
  }


  public OrderCreateDto totalShippingCostCurrencyId(String totalShippingCostCurrencyId) {
    this.totalShippingCostCurrencyId = totalShippingCostCurrencyId;
    return this;
  }

  /**
   * Get totalShippingCostCurrencyId
   * @return totalShippingCostCurrencyId
   */
  @javax.annotation.Nullable
  public String getTotalShippingCostCurrencyId() {
    return totalShippingCostCurrencyId;
  }

  public void setTotalShippingCostCurrencyId(String totalShippingCostCurrencyId) {
    this.totalShippingCostCurrencyId = totalShippingCostCurrencyId;
  }


  public OrderCreateDto totalShippingTax(Double totalShippingTax) {
    this.totalShippingTax = totalShippingTax;
    return this;
  }

  /**
   * Get totalShippingTax
   * @return totalShippingTax
   */
  @javax.annotation.Nullable
  public Double getTotalShippingTax() {
    return totalShippingTax;
  }

  public void setTotalShippingTax(Double totalShippingTax) {
    this.totalShippingTax = totalShippingTax;
  }


  public OrderCreateDto totalShippingTaxCurrencyId(String totalShippingTaxCurrencyId) {
    this.totalShippingTaxCurrencyId = totalShippingTaxCurrencyId;
    return this;
  }

  /**
   * Get totalShippingTaxCurrencyId
   * @return totalShippingTaxCurrencyId
   */
  @javax.annotation.Nullable
  public String getTotalShippingTaxCurrencyId() {
    return totalShippingTaxCurrencyId;
  }

  public void setTotalShippingTaxCurrencyId(String totalShippingTaxCurrencyId) {
    this.totalShippingTaxCurrencyId = totalShippingTaxCurrencyId;
  }


  public OrderCreateDto totalWithheldTax(Double totalWithheldTax) {
    this.totalWithheldTax = totalWithheldTax;
    return this;
  }

  /**
   * Get totalWithheldTax
   * @return totalWithheldTax
   */
  @javax.annotation.Nullable
  public Double getTotalWithheldTax() {
    return totalWithheldTax;
  }

  public void setTotalWithheldTax(Double totalWithheldTax) {
    this.totalWithheldTax = totalWithheldTax;
  }


  public OrderCreateDto totalWithheldTaxCurrencyId(String totalWithheldTaxCurrencyId) {
    this.totalWithheldTaxCurrencyId = totalWithheldTaxCurrencyId;
    return this;
  }

  /**
   * Get totalWithheldTaxCurrencyId
   * @return totalWithheldTaxCurrencyId
   */
  @javax.annotation.Nullable
  public String getTotalWithheldTaxCurrencyId() {
    return totalWithheldTaxCurrencyId;
  }

  public void setTotalWithheldTaxCurrencyId(String totalWithheldTaxCurrencyId) {
    this.totalWithheldTaxCurrencyId = totalWithheldTaxCurrencyId;
  }


  public OrderCreateDto totalTaxBase(Double totalTaxBase) {
    this.totalTaxBase = totalTaxBase;
    return this;
  }

  /**
   * Get totalTaxBase
   * @return totalTaxBase
   */
  @javax.annotation.Nullable
  public Double getTotalTaxBase() {
    return totalTaxBase;
  }

  public void setTotalTaxBase(Double totalTaxBase) {
    this.totalTaxBase = totalTaxBase;
  }


  public OrderCreateDto totalTaxBaseCurrencyId(String totalTaxBaseCurrencyId) {
    this.totalTaxBaseCurrencyId = totalTaxBaseCurrencyId;
    return this;
  }

  /**
   * Get totalTaxBaseCurrencyId
   * @return totalTaxBaseCurrencyId
   */
  @javax.annotation.Nullable
  public String getTotalTaxBaseCurrencyId() {
    return totalTaxBaseCurrencyId;
  }

  public void setTotalTaxBaseCurrencyId(String totalTaxBaseCurrencyId) {
    this.totalTaxBaseCurrencyId = totalTaxBaseCurrencyId;
  }


  public OrderCreateDto totalTaxes(Double totalTaxes) {
    this.totalTaxes = totalTaxes;
    return this;
  }

  /**
   * Get totalTaxes
   * @return totalTaxes
   */
  @javax.annotation.Nullable
  public Double getTotalTaxes() {
    return totalTaxes;
  }

  public void setTotalTaxes(Double totalTaxes) {
    this.totalTaxes = totalTaxes;
  }


  public OrderCreateDto totalTaxesCurrencyId(String totalTaxesCurrencyId) {
    this.totalTaxesCurrencyId = totalTaxesCurrencyId;
    return this;
  }

  /**
   * Get totalTaxesCurrencyId
   * @return totalTaxesCurrencyId
   */
  @javax.annotation.Nullable
  public String getTotalTaxesCurrencyId() {
    return totalTaxesCurrencyId;
  }

  public void setTotalTaxesCurrencyId(String totalTaxesCurrencyId) {
    this.totalTaxesCurrencyId = totalTaxesCurrencyId;
  }


  public OrderCreateDto totalGlobalSurcharges(Double totalGlobalSurcharges) {
    this.totalGlobalSurcharges = totalGlobalSurcharges;
    return this;
  }

  /**
   * Get totalGlobalSurcharges
   * @return totalGlobalSurcharges
   */
  @javax.annotation.Nullable
  public Double getTotalGlobalSurcharges() {
    return totalGlobalSurcharges;
  }

  public void setTotalGlobalSurcharges(Double totalGlobalSurcharges) {
    this.totalGlobalSurcharges = totalGlobalSurcharges;
  }


  public OrderCreateDto totalGlobalSurchargesCurrencyId(String totalGlobalSurchargesCurrencyId) {
    this.totalGlobalSurchargesCurrencyId = totalGlobalSurchargesCurrencyId;
    return this;
  }

  /**
   * Get totalGlobalSurchargesCurrencyId
   * @return totalGlobalSurchargesCurrencyId
   */
  @javax.annotation.Nullable
  public String getTotalGlobalSurchargesCurrencyId() {
    return totalGlobalSurchargesCurrencyId;
  }

  public void setTotalGlobalSurchargesCurrencyId(String totalGlobalSurchargesCurrencyId) {
    this.totalGlobalSurchargesCurrencyId = totalGlobalSurchargesCurrencyId;
  }


  public OrderCreateDto totalGlobalDiscounts(Double totalGlobalDiscounts) {
    this.totalGlobalDiscounts = totalGlobalDiscounts;
    return this;
  }

  /**
   * Get totalGlobalDiscounts
   * @return totalGlobalDiscounts
   */
  @javax.annotation.Nullable
  public Double getTotalGlobalDiscounts() {
    return totalGlobalDiscounts;
  }

  public void setTotalGlobalDiscounts(Double totalGlobalDiscounts) {
    this.totalGlobalDiscounts = totalGlobalDiscounts;
  }


  public OrderCreateDto totalGlobalDiscountsCurrencyId(String totalGlobalDiscountsCurrencyId) {
    this.totalGlobalDiscountsCurrencyId = totalGlobalDiscountsCurrencyId;
    return this;
  }

  /**
   * Get totalGlobalDiscountsCurrencyId
   * @return totalGlobalDiscountsCurrencyId
   */
  @javax.annotation.Nullable
  public String getTotalGlobalDiscountsCurrencyId() {
    return totalGlobalDiscountsCurrencyId;
  }

  public void setTotalGlobalDiscountsCurrencyId(String totalGlobalDiscountsCurrencyId) {
    this.totalGlobalDiscountsCurrencyId = totalGlobalDiscountsCurrencyId;
  }


  public OrderCreateDto total(Double total) {
    this.total = total;
    return this;
  }

  /**
   * Get total
   * @return total
   */
  @javax.annotation.Nullable
  public Double getTotal() {
    return total;
  }

  public void setTotal(Double total) {
    this.total = total;
  }


  public OrderCreateDto totalCurrencyId(String totalCurrencyId) {
    this.totalCurrencyId = totalCurrencyId;
    return this;
  }

  /**
   * Get totalCurrencyId
   * @return totalCurrencyId
   */
  @javax.annotation.Nullable
  public String getTotalCurrencyId() {
    return totalCurrencyId;
  }

  public void setTotalCurrencyId(String totalCurrencyId) {
    this.totalCurrencyId = totalCurrencyId;
  }


  public OrderCreateDto costCalculationMethod(CostCalculationMethodEnum costCalculationMethod) {
    this.costCalculationMethod = costCalculationMethod;
    return this;
  }

  /**
   * Get costCalculationMethod
   * @return costCalculationMethod
   */
  @javax.annotation.Nullable
  public CostCalculationMethodEnum getCostCalculationMethod() {
    return costCalculationMethod;
  }

  public void setCostCalculationMethod(CostCalculationMethodEnum costCalculationMethod) {
    this.costCalculationMethod = costCalculationMethod;
  }


  public OrderCreateDto taxCalculationMethod(TaxCalculationMethodEnum taxCalculationMethod) {
    this.taxCalculationMethod = taxCalculationMethod;
    return this;
  }

  /**
   * Get taxCalculationMethod
   * @return taxCalculationMethod
   */
  @javax.annotation.Nullable
  public TaxCalculationMethodEnum getTaxCalculationMethod() {
    return taxCalculationMethod;
  }

  public void setTaxCalculationMethod(TaxCalculationMethodEnum taxCalculationMethod) {
    this.taxCalculationMethod = taxCalculationMethod;
  }


  public OrderCreateDto cartId(String cartId) {
    this.cartId = cartId;
    return this;
  }

  /**
   * Get cartId
   * @return cartId
   */
  @javax.annotation.Nullable
  public String getCartId() {
    return cartId;
  }

  public void setCartId(String cartId) {
    this.cartId = cartId;
  }


  public OrderCreateDto quoteId(String quoteId) {
    this.quoteId = quoteId;
    return this;
  }

  /**
   * Get quoteId
   * @return quoteId
   */
  @javax.annotation.Nullable
  public String getQuoteId() {
    return quoteId;
  }

  public void setQuoteId(String quoteId) {
    this.quoteId = quoteId;
  }


  public OrderCreateDto walletId(String walletId) {
    this.walletId = walletId;
    return this;
  }

  /**
   * Get walletId
   * @return walletId
   */
  @javax.annotation.Nullable
  public String getWalletId() {
    return walletId;
  }

  public void setWalletId(String walletId) {
    this.walletId = walletId;
  }


  public OrderCreateDto parentOrderId(String parentOrderId) {
    this.parentOrderId = parentOrderId;
    return this;
  }

  /**
   * Get parentOrderId
   * @return parentOrderId
   */
  @javax.annotation.Nullable
  public String getParentOrderId() {
    return parentOrderId;
  }

  public void setParentOrderId(String parentOrderId) {
    this.parentOrderId = parentOrderId;
  }


  public OrderCreateDto shippingMethodId(String shippingMethodId) {
    this.shippingMethodId = shippingMethodId;
    return this;
  }

  /**
   * Get shippingMethodId
   * @return shippingMethodId
   */
  @javax.annotation.Nullable
  public String getShippingMethodId() {
    return shippingMethodId;
  }

  public void setShippingMethodId(String shippingMethodId) {
    this.shippingMethodId = shippingMethodId;
  }


  public OrderCreateDto billingLocationId(String billingLocationId) {
    this.billingLocationId = billingLocationId;
    return this;
  }

  /**
   * Get billingLocationId
   * @return billingLocationId
   */
  @javax.annotation.Nullable
  public String getBillingLocationId() {
    return billingLocationId;
  }

  public void setBillingLocationId(String billingLocationId) {
    this.billingLocationId = billingLocationId;
  }


  public OrderCreateDto customerNotes(String customerNotes) {
    this.customerNotes = customerNotes;
    return this;
  }

  /**
   * Get customerNotes
   * @return customerNotes
   */
  @javax.annotation.Nullable
  public String getCustomerNotes() {
    return customerNotes;
  }

  public void setCustomerNotes(String customerNotes) {
    this.customerNotes = customerNotes;
  }


  public OrderCreateDto orderStatus(OrderStatusEnum orderStatus) {
    this.orderStatus = orderStatus;
    return this;
  }

  /**
   * Get orderStatus
   * @return orderStatus
   */
  @javax.annotation.Nullable
  public OrderStatusEnum getOrderStatus() {
    return orderStatus;
  }

  public void setOrderStatus(OrderStatusEnum orderStatus) {
    this.orderStatus = orderStatus;
  }


  public OrderCreateDto quoteStatus(QuoteStatusEnum quoteStatus) {
    this.quoteStatus = quoteStatus;
    return this;
  }

  /**
   * Get quoteStatus
   * @return quoteStatus
   */
  @javax.annotation.Nullable
  public QuoteStatusEnum getQuoteStatus() {
    return quoteStatus;
  }

  public void setQuoteStatus(QuoteStatusEnum quoteStatus) {
    this.quoteStatus = quoteStatus;
  }


  public OrderCreateDto freightTerms(FreightTermsEnum freightTerms) {
    this.freightTerms = freightTerms;
    return this;
  }

  /**
   * Get freightTerms
   * @return freightTerms
   */
  @javax.annotation.Nullable
  public FreightTermsEnum getFreightTerms() {
    return freightTerms;
  }

  public void setFreightTerms(FreightTermsEnum freightTerms) {
    this.freightTerms = freightTerms;
  }


  public OrderCreateDto receiverTenantId(String receiverTenantId) {
    this.receiverTenantId = receiverTenantId;
    return this;
  }

  /**
   * Get receiverTenantId
   * @return receiverTenantId
   */
  @javax.annotation.Nullable
  public String getReceiverTenantId() {
    return receiverTenantId;
  }

  public void setReceiverTenantId(String receiverTenantId) {
    this.receiverTenantId = receiverTenantId;
  }


  public OrderCreateDto shippingLocationId(String shippingLocationId) {
    this.shippingLocationId = shippingLocationId;
    return this;
  }

  /**
   * Get shippingLocationId
   * @return shippingLocationId
   */
  @javax.annotation.Nullable
  public String getShippingLocationId() {
    return shippingLocationId;
  }

  public void setShippingLocationId(String shippingLocationId) {
    this.shippingLocationId = shippingLocationId;
  }


  public OrderCreateDto qualifiedIdentifier(String qualifiedIdentifier) {
    this.qualifiedIdentifier = qualifiedIdentifier;
    return this;
  }

  /**
   * Get qualifiedIdentifier
   * @return qualifiedIdentifier
   */
  @javax.annotation.Nullable
  public String getQualifiedIdentifier() {
    return qualifiedIdentifier;
  }

  public void setQualifiedIdentifier(String qualifiedIdentifier) {
    this.qualifiedIdentifier = qualifiedIdentifier;
  }


  public OrderCreateDto totalTaxesInUsd(Double totalTaxesInUsd) {
    this.totalTaxesInUsd = totalTaxesInUsd;
    return this;
  }

  /**
   * Get totalTaxesInUsd
   * @return totalTaxesInUsd
   */
  @javax.annotation.Nullable
  public Double getTotalTaxesInUsd() {
    return totalTaxesInUsd;
  }

  public void setTotalTaxesInUsd(Double totalTaxesInUsd) {
    this.totalTaxesInUsd = totalTaxesInUsd;
  }


  public OrderCreateDto totalDiscountsInUsd(Double totalDiscountsInUsd) {
    this.totalDiscountsInUsd = totalDiscountsInUsd;
    return this;
  }

  /**
   * Get totalDiscountsInUsd
   * @return totalDiscountsInUsd
   */
  @javax.annotation.Nullable
  public Double getTotalDiscountsInUsd() {
    return totalDiscountsInUsd;
  }

  public void setTotalDiscountsInUsd(Double totalDiscountsInUsd) {
    this.totalDiscountsInUsd = totalDiscountsInUsd;
  }


  public OrderCreateDto totalSurchargesInUsd(Double totalSurchargesInUsd) {
    this.totalSurchargesInUsd = totalSurchargesInUsd;
    return this;
  }

  /**
   * Get totalSurchargesInUsd
   * @return totalSurchargesInUsd
   */
  @javax.annotation.Nullable
  public Double getTotalSurchargesInUsd() {
    return totalSurchargesInUsd;
  }

  public void setTotalSurchargesInUsd(Double totalSurchargesInUsd) {
    this.totalSurchargesInUsd = totalSurchargesInUsd;
  }


  public OrderCreateDto totalShippingCostInUsd(Double totalShippingCostInUsd) {
    this.totalShippingCostInUsd = totalShippingCostInUsd;
    return this;
  }

  /**
   * Get totalShippingCostInUsd
   * @return totalShippingCostInUsd
   */
  @javax.annotation.Nullable
  public Double getTotalShippingCostInUsd() {
    return totalShippingCostInUsd;
  }

  public void setTotalShippingCostInUsd(Double totalShippingCostInUsd) {
    this.totalShippingCostInUsd = totalShippingCostInUsd;
  }


  public OrderCreateDto totalShippingTaxInUsd(Double totalShippingTaxInUsd) {
    this.totalShippingTaxInUsd = totalShippingTaxInUsd;
    return this;
  }

  /**
   * Get totalShippingTaxInUsd
   * @return totalShippingTaxInUsd
   */
  @javax.annotation.Nullable
  public Double getTotalShippingTaxInUsd() {
    return totalShippingTaxInUsd;
  }

  public void setTotalShippingTaxInUsd(Double totalShippingTaxInUsd) {
    this.totalShippingTaxInUsd = totalShippingTaxInUsd;
  }


  public OrderCreateDto totalAmountInUsd(Double totalAmountInUsd) {
    this.totalAmountInUsd = totalAmountInUsd;
    return this;
  }

  /**
   * Get totalAmountInUsd
   * @return totalAmountInUsd
   */
  @javax.annotation.Nullable
  public Double getTotalAmountInUsd() {
    return totalAmountInUsd;
  }

  public void setTotalAmountInUsd(Double totalAmountInUsd) {
    this.totalAmountInUsd = totalAmountInUsd;
  }


  public OrderCreateDto effectiveTo(OffsetDateTime effectiveTo) {
    this.effectiveTo = effectiveTo;
    return this;
  }

  /**
   * Get effectiveTo
   * @return effectiveTo
   */
  @javax.annotation.Nullable
  public OffsetDateTime getEffectiveTo() {
    return effectiveTo;
  }

  public void setEffectiveTo(OffsetDateTime effectiveTo) {
    this.effectiveTo = effectiveTo;
  }


  public OrderCreateDto effectiveFrom(OffsetDateTime effectiveFrom) {
    this.effectiveFrom = effectiveFrom;
    return this;
  }

  /**
   * Get effectiveFrom
   * @return effectiveFrom
   */
  @javax.annotation.Nullable
  public OffsetDateTime getEffectiveFrom() {
    return effectiveFrom;
  }

  public void setEffectiveFrom(OffsetDateTime effectiveFrom) {
    this.effectiveFrom = effectiveFrom;
  }


  public OrderCreateDto orderLines(List<OrderLineCreateDto> orderLines) {
    this.orderLines = orderLines;
    return this;
  }

  public OrderCreateDto addOrderLinesItem(OrderLineCreateDto orderLinesItem) {
    if (this.orderLines == null) {
      this.orderLines = new ArrayList<>();
    }
    this.orderLines.add(orderLinesItem);
    return this;
  }

  /**
   * Get orderLines
   * @return orderLines
   */
  @javax.annotation.Nullable
  public List<OrderLineCreateDto> getOrderLines() {
    return orderLines;
  }

  public void setOrderLines(List<OrderLineCreateDto> orderLines) {
    this.orderLines = orderLines;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderCreateDto orderCreateDto = (OrderCreateDto) o;
    return Objects.equals(this.id, orderCreateDto.id) &&
        Objects.equals(this.timestamp, orderCreateDto.timestamp) &&
        Objects.equals(this.closed, orderCreateDto.closed) &&
        Objects.equals(this.title, orderCreateDto.title) &&
        Objects.equals(this.priceListId, orderCreateDto.priceListId) &&
        Objects.equals(this.description, orderCreateDto.description) &&
        Objects.equals(this.individualId, orderCreateDto.individualId) &&
        Objects.equals(this.paymentTermId, orderCreateDto.paymentTermId) &&
        Objects.equals(this.organizationId, orderCreateDto.organizationId) &&
        Objects.equals(this.firstName, orderCreateDto.firstName) &&
        Objects.equals(this.lastName, orderCreateDto.lastName) &&
        Objects.equals(this.companyName, orderCreateDto.companyName) &&
        Objects.equals(this.billingEmail, orderCreateDto.billingEmail) &&
        Objects.equals(this.addressLine1, orderCreateDto.addressLine1) &&
        Objects.equals(this.addressLine2, orderCreateDto.addressLine2) &&
        Objects.equals(this.postalCode, orderCreateDto.postalCode) &&
        Objects.equals(this.countryId, orderCreateDto.countryId) &&
        Objects.equals(this.stateId, orderCreateDto.stateId) &&
        Objects.equals(this.cityId, orderCreateDto.cityId) &&
        Objects.equals(this.forexRate, orderCreateDto.forexRate) &&
        Objects.equals(this.currencyId, orderCreateDto.currencyId) &&
        Objects.equals(this.totalDetail, orderCreateDto.totalDetail) &&
        Objects.equals(this.totalDetailCurrencyId, orderCreateDto.totalDetailCurrencyId) &&
        Objects.equals(this.totalProfit, orderCreateDto.totalProfit) &&
        Objects.equals(this.totalProfitCurrencyId, orderCreateDto.totalProfitCurrencyId) &&
        Objects.equals(this.totalDiscounts, orderCreateDto.totalDiscounts) &&
        Objects.equals(this.totalDiscountsCurrencyId, orderCreateDto.totalDiscountsCurrencyId) &&
        Objects.equals(this.totalSurcharges, orderCreateDto.totalSurcharges) &&
        Objects.equals(this.totalSurchargesCurrencyId, orderCreateDto.totalSurchargesCurrencyId) &&
        Objects.equals(this.totalShippingCost, orderCreateDto.totalShippingCost) &&
        Objects.equals(this.totalShippingCostCurrencyId, orderCreateDto.totalShippingCostCurrencyId) &&
        Objects.equals(this.totalShippingTax, orderCreateDto.totalShippingTax) &&
        Objects.equals(this.totalShippingTaxCurrencyId, orderCreateDto.totalShippingTaxCurrencyId) &&
        Objects.equals(this.totalWithheldTax, orderCreateDto.totalWithheldTax) &&
        Objects.equals(this.totalWithheldTaxCurrencyId, orderCreateDto.totalWithheldTaxCurrencyId) &&
        Objects.equals(this.totalTaxBase, orderCreateDto.totalTaxBase) &&
        Objects.equals(this.totalTaxBaseCurrencyId, orderCreateDto.totalTaxBaseCurrencyId) &&
        Objects.equals(this.totalTaxes, orderCreateDto.totalTaxes) &&
        Objects.equals(this.totalTaxesCurrencyId, orderCreateDto.totalTaxesCurrencyId) &&
        Objects.equals(this.totalGlobalSurcharges, orderCreateDto.totalGlobalSurcharges) &&
        Objects.equals(this.totalGlobalSurchargesCurrencyId, orderCreateDto.totalGlobalSurchargesCurrencyId) &&
        Objects.equals(this.totalGlobalDiscounts, orderCreateDto.totalGlobalDiscounts) &&
        Objects.equals(this.totalGlobalDiscountsCurrencyId, orderCreateDto.totalGlobalDiscountsCurrencyId) &&
        Objects.equals(this.total, orderCreateDto.total) &&
        Objects.equals(this.totalCurrencyId, orderCreateDto.totalCurrencyId) &&
        Objects.equals(this.costCalculationMethod, orderCreateDto.costCalculationMethod) &&
        Objects.equals(this.taxCalculationMethod, orderCreateDto.taxCalculationMethod) &&
        Objects.equals(this.cartId, orderCreateDto.cartId) &&
        Objects.equals(this.quoteId, orderCreateDto.quoteId) &&
        Objects.equals(this.walletId, orderCreateDto.walletId) &&
        Objects.equals(this.parentOrderId, orderCreateDto.parentOrderId) &&
        Objects.equals(this.shippingMethodId, orderCreateDto.shippingMethodId) &&
        Objects.equals(this.billingLocationId, orderCreateDto.billingLocationId) &&
        Objects.equals(this.customerNotes, orderCreateDto.customerNotes) &&
        Objects.equals(this.orderStatus, orderCreateDto.orderStatus) &&
        Objects.equals(this.quoteStatus, orderCreateDto.quoteStatus) &&
        Objects.equals(this.freightTerms, orderCreateDto.freightTerms) &&
        Objects.equals(this.receiverTenantId, orderCreateDto.receiverTenantId) &&
        Objects.equals(this.shippingLocationId, orderCreateDto.shippingLocationId) &&
        Objects.equals(this.qualifiedIdentifier, orderCreateDto.qualifiedIdentifier) &&
        Objects.equals(this.totalTaxesInUsd, orderCreateDto.totalTaxesInUsd) &&
        Objects.equals(this.totalDiscountsInUsd, orderCreateDto.totalDiscountsInUsd) &&
        Objects.equals(this.totalSurchargesInUsd, orderCreateDto.totalSurchargesInUsd) &&
        Objects.equals(this.totalShippingCostInUsd, orderCreateDto.totalShippingCostInUsd) &&
        Objects.equals(this.totalShippingTaxInUsd, orderCreateDto.totalShippingTaxInUsd) &&
        Objects.equals(this.totalAmountInUsd, orderCreateDto.totalAmountInUsd) &&
        Objects.equals(this.effectiveTo, orderCreateDto.effectiveTo) &&
        Objects.equals(this.effectiveFrom, orderCreateDto.effectiveFrom) &&
        Objects.equals(this.orderLines, orderCreateDto.orderLines);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, timestamp, closed, title, priceListId, description, individualId, paymentTermId, organizationId, firstName, lastName, companyName, billingEmail, addressLine1, addressLine2, postalCode, countryId, stateId, cityId, forexRate, currencyId, totalDetail, totalDetailCurrencyId, totalProfit, totalProfitCurrencyId, totalDiscounts, totalDiscountsCurrencyId, totalSurcharges, totalSurchargesCurrencyId, totalShippingCost, totalShippingCostCurrencyId, totalShippingTax, totalShippingTaxCurrencyId, totalWithheldTax, totalWithheldTaxCurrencyId, totalTaxBase, totalTaxBaseCurrencyId, totalTaxes, totalTaxesCurrencyId, totalGlobalSurcharges, totalGlobalSurchargesCurrencyId, totalGlobalDiscounts, totalGlobalDiscountsCurrencyId, total, totalCurrencyId, costCalculationMethod, taxCalculationMethod, cartId, quoteId, walletId, parentOrderId, shippingMethodId, billingLocationId, customerNotes, orderStatus, quoteStatus, freightTerms, receiverTenantId, shippingLocationId, qualifiedIdentifier, totalTaxesInUsd, totalDiscountsInUsd, totalSurchargesInUsd, totalShippingCostInUsd, totalShippingTaxInUsd, totalAmountInUsd, effectiveTo, effectiveFrom, orderLines);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderCreateDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    closed: ").append(toIndentedString(closed)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    priceListId: ").append(toIndentedString(priceListId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    individualId: ").append(toIndentedString(individualId)).append("\n");
    sb.append("    paymentTermId: ").append(toIndentedString(paymentTermId)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    billingEmail: ").append(toIndentedString(billingEmail)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    countryId: ").append(toIndentedString(countryId)).append("\n");
    sb.append("    stateId: ").append(toIndentedString(stateId)).append("\n");
    sb.append("    cityId: ").append(toIndentedString(cityId)).append("\n");
    sb.append("    forexRate: ").append(toIndentedString(forexRate)).append("\n");
    sb.append("    currencyId: ").append(toIndentedString(currencyId)).append("\n");
    sb.append("    totalDetail: ").append(toIndentedString(totalDetail)).append("\n");
    sb.append("    totalDetailCurrencyId: ").append(toIndentedString(totalDetailCurrencyId)).append("\n");
    sb.append("    totalProfit: ").append(toIndentedString(totalProfit)).append("\n");
    sb.append("    totalProfitCurrencyId: ").append(toIndentedString(totalProfitCurrencyId)).append("\n");
    sb.append("    totalDiscounts: ").append(toIndentedString(totalDiscounts)).append("\n");
    sb.append("    totalDiscountsCurrencyId: ").append(toIndentedString(totalDiscountsCurrencyId)).append("\n");
    sb.append("    totalSurcharges: ").append(toIndentedString(totalSurcharges)).append("\n");
    sb.append("    totalSurchargesCurrencyId: ").append(toIndentedString(totalSurchargesCurrencyId)).append("\n");
    sb.append("    totalShippingCost: ").append(toIndentedString(totalShippingCost)).append("\n");
    sb.append("    totalShippingCostCurrencyId: ").append(toIndentedString(totalShippingCostCurrencyId)).append("\n");
    sb.append("    totalShippingTax: ").append(toIndentedString(totalShippingTax)).append("\n");
    sb.append("    totalShippingTaxCurrencyId: ").append(toIndentedString(totalShippingTaxCurrencyId)).append("\n");
    sb.append("    totalWithheldTax: ").append(toIndentedString(totalWithheldTax)).append("\n");
    sb.append("    totalWithheldTaxCurrencyId: ").append(toIndentedString(totalWithheldTaxCurrencyId)).append("\n");
    sb.append("    totalTaxBase: ").append(toIndentedString(totalTaxBase)).append("\n");
    sb.append("    totalTaxBaseCurrencyId: ").append(toIndentedString(totalTaxBaseCurrencyId)).append("\n");
    sb.append("    totalTaxes: ").append(toIndentedString(totalTaxes)).append("\n");
    sb.append("    totalTaxesCurrencyId: ").append(toIndentedString(totalTaxesCurrencyId)).append("\n");
    sb.append("    totalGlobalSurcharges: ").append(toIndentedString(totalGlobalSurcharges)).append("\n");
    sb.append("    totalGlobalSurchargesCurrencyId: ").append(toIndentedString(totalGlobalSurchargesCurrencyId)).append("\n");
    sb.append("    totalGlobalDiscounts: ").append(toIndentedString(totalGlobalDiscounts)).append("\n");
    sb.append("    totalGlobalDiscountsCurrencyId: ").append(toIndentedString(totalGlobalDiscountsCurrencyId)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    totalCurrencyId: ").append(toIndentedString(totalCurrencyId)).append("\n");
    sb.append("    costCalculationMethod: ").append(toIndentedString(costCalculationMethod)).append("\n");
    sb.append("    taxCalculationMethod: ").append(toIndentedString(taxCalculationMethod)).append("\n");
    sb.append("    cartId: ").append(toIndentedString(cartId)).append("\n");
    sb.append("    quoteId: ").append(toIndentedString(quoteId)).append("\n");
    sb.append("    walletId: ").append(toIndentedString(walletId)).append("\n");
    sb.append("    parentOrderId: ").append(toIndentedString(parentOrderId)).append("\n");
    sb.append("    shippingMethodId: ").append(toIndentedString(shippingMethodId)).append("\n");
    sb.append("    billingLocationId: ").append(toIndentedString(billingLocationId)).append("\n");
    sb.append("    customerNotes: ").append(toIndentedString(customerNotes)).append("\n");
    sb.append("    orderStatus: ").append(toIndentedString(orderStatus)).append("\n");
    sb.append("    quoteStatus: ").append(toIndentedString(quoteStatus)).append("\n");
    sb.append("    freightTerms: ").append(toIndentedString(freightTerms)).append("\n");
    sb.append("    receiverTenantId: ").append(toIndentedString(receiverTenantId)).append("\n");
    sb.append("    shippingLocationId: ").append(toIndentedString(shippingLocationId)).append("\n");
    sb.append("    qualifiedIdentifier: ").append(toIndentedString(qualifiedIdentifier)).append("\n");
    sb.append("    totalTaxesInUsd: ").append(toIndentedString(totalTaxesInUsd)).append("\n");
    sb.append("    totalDiscountsInUsd: ").append(toIndentedString(totalDiscountsInUsd)).append("\n");
    sb.append("    totalSurchargesInUsd: ").append(toIndentedString(totalSurchargesInUsd)).append("\n");
    sb.append("    totalShippingCostInUsd: ").append(toIndentedString(totalShippingCostInUsd)).append("\n");
    sb.append("    totalShippingTaxInUsd: ").append(toIndentedString(totalShippingTaxInUsd)).append("\n");
    sb.append("    totalAmountInUsd: ").append(toIndentedString(totalAmountInUsd)).append("\n");
    sb.append("    effectiveTo: ").append(toIndentedString(effectiveTo)).append("\n");
    sb.append("    effectiveFrom: ").append(toIndentedString(effectiveFrom)).append("\n");
    sb.append("    orderLines: ").append(toIndentedString(orderLines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("timestamp");
    openapiFields.add("closed");
    openapiFields.add("title");
    openapiFields.add("priceListId");
    openapiFields.add("description");
    openapiFields.add("individualId");
    openapiFields.add("paymentTermId");
    openapiFields.add("organizationId");
    openapiFields.add("firstName");
    openapiFields.add("lastName");
    openapiFields.add("companyName");
    openapiFields.add("billingEmail");
    openapiFields.add("addressLine1");
    openapiFields.add("addressLine2");
    openapiFields.add("postalCode");
    openapiFields.add("countryId");
    openapiFields.add("stateId");
    openapiFields.add("cityId");
    openapiFields.add("forexRate");
    openapiFields.add("currencyId");
    openapiFields.add("totalDetail");
    openapiFields.add("totalDetailCurrencyId");
    openapiFields.add("totalProfit");
    openapiFields.add("totalProfitCurrencyId");
    openapiFields.add("totalDiscounts");
    openapiFields.add("totalDiscountsCurrencyId");
    openapiFields.add("totalSurcharges");
    openapiFields.add("totalSurchargesCurrencyId");
    openapiFields.add("totalShippingCost");
    openapiFields.add("totalShippingCostCurrencyId");
    openapiFields.add("totalShippingTax");
    openapiFields.add("totalShippingTaxCurrencyId");
    openapiFields.add("totalWithheldTax");
    openapiFields.add("totalWithheldTaxCurrencyId");
    openapiFields.add("totalTaxBase");
    openapiFields.add("totalTaxBaseCurrencyId");
    openapiFields.add("totalTaxes");
    openapiFields.add("totalTaxesCurrencyId");
    openapiFields.add("totalGlobalSurcharges");
    openapiFields.add("totalGlobalSurchargesCurrencyId");
    openapiFields.add("totalGlobalDiscounts");
    openapiFields.add("totalGlobalDiscountsCurrencyId");
    openapiFields.add("total");
    openapiFields.add("totalCurrencyId");
    openapiFields.add("costCalculationMethod");
    openapiFields.add("taxCalculationMethod");
    openapiFields.add("cartId");
    openapiFields.add("quoteId");
    openapiFields.add("walletId");
    openapiFields.add("parentOrderId");
    openapiFields.add("shippingMethodId");
    openapiFields.add("billingLocationId");
    openapiFields.add("customerNotes");
    openapiFields.add("orderStatus");
    openapiFields.add("quoteStatus");
    openapiFields.add("freightTerms");
    openapiFields.add("receiverTenantId");
    openapiFields.add("shippingLocationId");
    openapiFields.add("qualifiedIdentifier");
    openapiFields.add("totalTaxesInUsd");
    openapiFields.add("totalDiscountsInUsd");
    openapiFields.add("totalSurchargesInUsd");
    openapiFields.add("totalShippingCostInUsd");
    openapiFields.add("totalShippingTaxInUsd");
    openapiFields.add("totalAmountInUsd");
    openapiFields.add("effectiveTo");
    openapiFields.add("effectiveFrom");
    openapiFields.add("orderLines");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OrderCreateDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OrderCreateDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OrderCreateDto is not found in the empty JSON string", OrderCreateDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OrderCreateDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OrderCreateDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("priceListId") != null && !jsonObj.get("priceListId").isJsonNull()) && !jsonObj.get("priceListId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `priceListId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("priceListId").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("individualId") != null && !jsonObj.get("individualId").isJsonNull()) && !jsonObj.get("individualId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `individualId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("individualId").toString()));
      }
      if ((jsonObj.get("paymentTermId") != null && !jsonObj.get("paymentTermId").isJsonNull()) && !jsonObj.get("paymentTermId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paymentTermId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymentTermId").toString()));
      }
      if ((jsonObj.get("organizationId") != null && !jsonObj.get("organizationId").isJsonNull()) && !jsonObj.get("organizationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `organizationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("organizationId").toString()));
      }
      if ((jsonObj.get("firstName") != null && !jsonObj.get("firstName").isJsonNull()) && !jsonObj.get("firstName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `firstName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("firstName").toString()));
      }
      if ((jsonObj.get("lastName") != null && !jsonObj.get("lastName").isJsonNull()) && !jsonObj.get("lastName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lastName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastName").toString()));
      }
      if ((jsonObj.get("companyName") != null && !jsonObj.get("companyName").isJsonNull()) && !jsonObj.get("companyName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `companyName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyName").toString()));
      }
      if ((jsonObj.get("billingEmail") != null && !jsonObj.get("billingEmail").isJsonNull()) && !jsonObj.get("billingEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `billingEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("billingEmail").toString()));
      }
      if ((jsonObj.get("addressLine1") != null && !jsonObj.get("addressLine1").isJsonNull()) && !jsonObj.get("addressLine1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `addressLine1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addressLine1").toString()));
      }
      if ((jsonObj.get("addressLine2") != null && !jsonObj.get("addressLine2").isJsonNull()) && !jsonObj.get("addressLine2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `addressLine2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addressLine2").toString()));
      }
      if ((jsonObj.get("postalCode") != null && !jsonObj.get("postalCode").isJsonNull()) && !jsonObj.get("postalCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `postalCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("postalCode").toString()));
      }
      if ((jsonObj.get("countryId") != null && !jsonObj.get("countryId").isJsonNull()) && !jsonObj.get("countryId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `countryId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("countryId").toString()));
      }
      if ((jsonObj.get("stateId") != null && !jsonObj.get("stateId").isJsonNull()) && !jsonObj.get("stateId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stateId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stateId").toString()));
      }
      if ((jsonObj.get("cityId") != null && !jsonObj.get("cityId").isJsonNull()) && !jsonObj.get("cityId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cityId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cityId").toString()));
      }
      if ((jsonObj.get("currencyId") != null && !jsonObj.get("currencyId").isJsonNull()) && !jsonObj.get("currencyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currencyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currencyId").toString()));
      }
      if ((jsonObj.get("totalDetailCurrencyId") != null && !jsonObj.get("totalDetailCurrencyId").isJsonNull()) && !jsonObj.get("totalDetailCurrencyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `totalDetailCurrencyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("totalDetailCurrencyId").toString()));
      }
      if ((jsonObj.get("totalProfitCurrencyId") != null && !jsonObj.get("totalProfitCurrencyId").isJsonNull()) && !jsonObj.get("totalProfitCurrencyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `totalProfitCurrencyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("totalProfitCurrencyId").toString()));
      }
      if ((jsonObj.get("totalDiscountsCurrencyId") != null && !jsonObj.get("totalDiscountsCurrencyId").isJsonNull()) && !jsonObj.get("totalDiscountsCurrencyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `totalDiscountsCurrencyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("totalDiscountsCurrencyId").toString()));
      }
      if ((jsonObj.get("totalSurchargesCurrencyId") != null && !jsonObj.get("totalSurchargesCurrencyId").isJsonNull()) && !jsonObj.get("totalSurchargesCurrencyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `totalSurchargesCurrencyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("totalSurchargesCurrencyId").toString()));
      }
      if ((jsonObj.get("totalShippingCostCurrencyId") != null && !jsonObj.get("totalShippingCostCurrencyId").isJsonNull()) && !jsonObj.get("totalShippingCostCurrencyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `totalShippingCostCurrencyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("totalShippingCostCurrencyId").toString()));
      }
      if ((jsonObj.get("totalShippingTaxCurrencyId") != null && !jsonObj.get("totalShippingTaxCurrencyId").isJsonNull()) && !jsonObj.get("totalShippingTaxCurrencyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `totalShippingTaxCurrencyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("totalShippingTaxCurrencyId").toString()));
      }
      if ((jsonObj.get("totalWithheldTaxCurrencyId") != null && !jsonObj.get("totalWithheldTaxCurrencyId").isJsonNull()) && !jsonObj.get("totalWithheldTaxCurrencyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `totalWithheldTaxCurrencyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("totalWithheldTaxCurrencyId").toString()));
      }
      if ((jsonObj.get("totalTaxBaseCurrencyId") != null && !jsonObj.get("totalTaxBaseCurrencyId").isJsonNull()) && !jsonObj.get("totalTaxBaseCurrencyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `totalTaxBaseCurrencyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("totalTaxBaseCurrencyId").toString()));
      }
      if ((jsonObj.get("totalTaxesCurrencyId") != null && !jsonObj.get("totalTaxesCurrencyId").isJsonNull()) && !jsonObj.get("totalTaxesCurrencyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `totalTaxesCurrencyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("totalTaxesCurrencyId").toString()));
      }
      if ((jsonObj.get("totalGlobalSurchargesCurrencyId") != null && !jsonObj.get("totalGlobalSurchargesCurrencyId").isJsonNull()) && !jsonObj.get("totalGlobalSurchargesCurrencyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `totalGlobalSurchargesCurrencyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("totalGlobalSurchargesCurrencyId").toString()));
      }
      if ((jsonObj.get("totalGlobalDiscountsCurrencyId") != null && !jsonObj.get("totalGlobalDiscountsCurrencyId").isJsonNull()) && !jsonObj.get("totalGlobalDiscountsCurrencyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `totalGlobalDiscountsCurrencyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("totalGlobalDiscountsCurrencyId").toString()));
      }
      if ((jsonObj.get("totalCurrencyId") != null && !jsonObj.get("totalCurrencyId").isJsonNull()) && !jsonObj.get("totalCurrencyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `totalCurrencyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("totalCurrencyId").toString()));
      }
      if ((jsonObj.get("costCalculationMethod") != null && !jsonObj.get("costCalculationMethod").isJsonNull()) && !jsonObj.get("costCalculationMethod").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `costCalculationMethod` to be a primitive type in the JSON string but got `%s`", jsonObj.get("costCalculationMethod").toString()));
      }
      // validate the optional field `costCalculationMethod`
      if (jsonObj.get("costCalculationMethod") != null && !jsonObj.get("costCalculationMethod").isJsonNull()) {
        CostCalculationMethodEnum.validateJsonElement(jsonObj.get("costCalculationMethod"));
      }
      if ((jsonObj.get("taxCalculationMethod") != null && !jsonObj.get("taxCalculationMethod").isJsonNull()) && !jsonObj.get("taxCalculationMethod").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `taxCalculationMethod` to be a primitive type in the JSON string but got `%s`", jsonObj.get("taxCalculationMethod").toString()));
      }
      // validate the optional field `taxCalculationMethod`
      if (jsonObj.get("taxCalculationMethod") != null && !jsonObj.get("taxCalculationMethod").isJsonNull()) {
        TaxCalculationMethodEnum.validateJsonElement(jsonObj.get("taxCalculationMethod"));
      }
      if ((jsonObj.get("cartId") != null && !jsonObj.get("cartId").isJsonNull()) && !jsonObj.get("cartId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cartId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cartId").toString()));
      }
      if ((jsonObj.get("quoteId") != null && !jsonObj.get("quoteId").isJsonNull()) && !jsonObj.get("quoteId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `quoteId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("quoteId").toString()));
      }
      if ((jsonObj.get("walletId") != null && !jsonObj.get("walletId").isJsonNull()) && !jsonObj.get("walletId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `walletId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("walletId").toString()));
      }
      if ((jsonObj.get("parentOrderId") != null && !jsonObj.get("parentOrderId").isJsonNull()) && !jsonObj.get("parentOrderId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `parentOrderId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parentOrderId").toString()));
      }
      if ((jsonObj.get("shippingMethodId") != null && !jsonObj.get("shippingMethodId").isJsonNull()) && !jsonObj.get("shippingMethodId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shippingMethodId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shippingMethodId").toString()));
      }
      if ((jsonObj.get("billingLocationId") != null && !jsonObj.get("billingLocationId").isJsonNull()) && !jsonObj.get("billingLocationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `billingLocationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("billingLocationId").toString()));
      }
      if ((jsonObj.get("customerNotes") != null && !jsonObj.get("customerNotes").isJsonNull()) && !jsonObj.get("customerNotes").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customerNotes` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerNotes").toString()));
      }
      if ((jsonObj.get("orderStatus") != null && !jsonObj.get("orderStatus").isJsonNull()) && !jsonObj.get("orderStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `orderStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("orderStatus").toString()));
      }
      // validate the optional field `orderStatus`
      if (jsonObj.get("orderStatus") != null && !jsonObj.get("orderStatus").isJsonNull()) {
        OrderStatusEnum.validateJsonElement(jsonObj.get("orderStatus"));
      }
      if ((jsonObj.get("quoteStatus") != null && !jsonObj.get("quoteStatus").isJsonNull()) && !jsonObj.get("quoteStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `quoteStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("quoteStatus").toString()));
      }
      // validate the optional field `quoteStatus`
      if (jsonObj.get("quoteStatus") != null && !jsonObj.get("quoteStatus").isJsonNull()) {
        QuoteStatusEnum.validateJsonElement(jsonObj.get("quoteStatus"));
      }
      if ((jsonObj.get("freightTerms") != null && !jsonObj.get("freightTerms").isJsonNull()) && !jsonObj.get("freightTerms").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `freightTerms` to be a primitive type in the JSON string but got `%s`", jsonObj.get("freightTerms").toString()));
      }
      // validate the optional field `freightTerms`
      if (jsonObj.get("freightTerms") != null && !jsonObj.get("freightTerms").isJsonNull()) {
        FreightTermsEnum.validateJsonElement(jsonObj.get("freightTerms"));
      }
      if ((jsonObj.get("receiverTenantId") != null && !jsonObj.get("receiverTenantId").isJsonNull()) && !jsonObj.get("receiverTenantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `receiverTenantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("receiverTenantId").toString()));
      }
      if ((jsonObj.get("shippingLocationId") != null && !jsonObj.get("shippingLocationId").isJsonNull()) && !jsonObj.get("shippingLocationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shippingLocationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shippingLocationId").toString()));
      }
      if ((jsonObj.get("qualifiedIdentifier") != null && !jsonObj.get("qualifiedIdentifier").isJsonNull()) && !jsonObj.get("qualifiedIdentifier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `qualifiedIdentifier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("qualifiedIdentifier").toString()));
      }
      if (jsonObj.get("orderLines") != null && !jsonObj.get("orderLines").isJsonNull()) {
        JsonArray jsonArrayorderLines = jsonObj.getAsJsonArray("orderLines");
        if (jsonArrayorderLines != null) {
          // ensure the json data is an array
          if (!jsonObj.get("orderLines").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `orderLines` to be an array in the JSON string but got `%s`", jsonObj.get("orderLines").toString()));
          }

          // validate the optional field `orderLines` (array)
          for (int i = 0; i < jsonArrayorderLines.size(); i++) {
            OrderLineCreateDto.validateJsonElement(jsonArrayorderLines.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrderCreateDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrderCreateDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrderCreateDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrderCreateDto.class));

       return (TypeAdapter<T>) new TypeAdapter<OrderCreateDto>() {
           @Override
           public void write(JsonWriter out, OrderCreateDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrderCreateDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OrderCreateDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OrderCreateDto
   * @throws IOException if the JSON string is invalid with respect to OrderCreateDto
   */
  public static OrderCreateDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrderCreateDto.class);
  }

  /**
   * Convert an instance of OrderCreateDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

