/*
 * SocialService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SocialPostReactionDto
 */
public class SocialPostReactionDtoTest {
    private final SocialPostReactionDto model = new SocialPostReactionDto();

    /**
     * Model tests for SocialPostReactionDto
     */
    @Test
    public void testSocialPostReactionDto() {
        // TODO: test SocialPostReactionDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'reaction'
     */
    @Test
    public void reactionTest() {
        // TODO: test reaction
    }

    /**
     * Test the property 'reactionValue'
     */
    @Test
    public void reactionValueTest() {
        // TODO: test reactionValue
    }

    /**
     * Test the property 'socialProfileId'
     */
    @Test
    public void socialProfileIdTest() {
        // TODO: test socialProfileId
    }

    /**
     * Test the property 'socialProfileName'
     */
    @Test
    public void socialProfileNameTest() {
        // TODO: test socialProfileName
    }

    /**
     * Test the property 'socialProfileAvatarUrl'
     */
    @Test
    public void socialProfileAvatarUrlTest() {
        // TODO: test socialProfileAvatarUrl
    }

    /**
     * Test the property 'socialProfileType'
     */
    @Test
    public void socialProfileTypeTest() {
        // TODO: test socialProfileType
    }

    /**
     * Test the property 'socialPostId'
     */
    @Test
    public void socialPostIdTest() {
        // TODO: test socialPostId
    }

}
