/*
 * TrustService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * SignedDocumentCreateDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-08T20:34:27.394016-05:00[America/Bogota]", comments = "Generator version: 7.9.0")
public class SignedDocumentCreateDto {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  private OffsetDateTime timestamp;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_CONTENT_TYPE = "contentType";
  @SerializedName(SERIALIZED_NAME_CONTENT_TYPE)
  private String contentType;

  public static final String SERIALIZED_NAME_CONTACT_ID = "contactId";
  @SerializedName(SERIALIZED_NAME_CONTACT_ID)
  private String contactId;

  /**
   * Gets or Sets documentStandard
   */
  @JsonAdapter(DocumentStandardEnum.Adapter.class)
  public enum DocumentStandardEnum {
    NONE("None"),
    
    UBL("Ubl"),
    
    PDF("Pdf"),
    
    XML("Xml"),
    
    EMAIL("Email"),
    
    JSON("Json"),
    
    OTHER("Other");

    private String value;

    DocumentStandardEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DocumentStandardEnum fromValue(String value) {
      for (DocumentStandardEnum b : DocumentStandardEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<DocumentStandardEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DocumentStandardEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DocumentStandardEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DocumentStandardEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DocumentStandardEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DOCUMENT_STANDARD = "documentStandard";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_STANDARD)
  private DocumentStandardEnum documentStandard;

  /**
   * Gets or Sets trustDocumentType
   */
  @JsonAdapter(TrustDocumentTypeEnum.Adapter.class)
  public enum TrustDocumentTypeEnum {
    UNKNOWN("Unknown"),
    
    INVOICE("Invoice"),
    
    CREDIT_NOTE("CreditNote"),
    
    DEBIT_NOTE("DebitNote"),
    
    CONTRACT("Contract"),
    
    CERTIFICATE("Certificate"),
    
    EMAIL("Email"),
    
    AUTHORITY_RESPONSE("AuthorityResponse"),
    
    OTHER("Other");

    private String value;

    TrustDocumentTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TrustDocumentTypeEnum fromValue(String value) {
      for (TrustDocumentTypeEnum b : TrustDocumentTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TrustDocumentTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TrustDocumentTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TrustDocumentTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TrustDocumentTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TrustDocumentTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TRUST_DOCUMENT_TYPE = "trustDocumentType";
  @SerializedName(SERIALIZED_NAME_TRUST_DOCUMENT_TYPE)
  private TrustDocumentTypeEnum trustDocumentType;

  public static final String SERIALIZED_NAME_CORRELATION_ID = "correlationId";
  @SerializedName(SERIALIZED_NAME_CORRELATION_ID)
  private String correlationId;

  public static final String SERIALIZED_NAME_EXTERNAL_REFERENCE = "externalReference";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_REFERENCE)
  private String externalReference;

  public SignedDocumentCreateDto() {
  }

  public SignedDocumentCreateDto id(UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }


  public SignedDocumentCreateDto timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nullable
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public SignedDocumentCreateDto url(String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nullable
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  public SignedDocumentCreateDto type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  public SignedDocumentCreateDto title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nonnull
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  public SignedDocumentCreateDto contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

  /**
   * Get contentType
   * @return contentType
   */
  @javax.annotation.Nullable
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }


  public SignedDocumentCreateDto contactId(String contactId) {
    this.contactId = contactId;
    return this;
  }

  /**
   * Get contactId
   * @return contactId
   */
  @javax.annotation.Nonnull
  public String getContactId() {
    return contactId;
  }

  public void setContactId(String contactId) {
    this.contactId = contactId;
  }


  public SignedDocumentCreateDto documentStandard(DocumentStandardEnum documentStandard) {
    this.documentStandard = documentStandard;
    return this;
  }

  /**
   * Get documentStandard
   * @return documentStandard
   */
  @javax.annotation.Nullable
  public DocumentStandardEnum getDocumentStandard() {
    return documentStandard;
  }

  public void setDocumentStandard(DocumentStandardEnum documentStandard) {
    this.documentStandard = documentStandard;
  }


  public SignedDocumentCreateDto trustDocumentType(TrustDocumentTypeEnum trustDocumentType) {
    this.trustDocumentType = trustDocumentType;
    return this;
  }

  /**
   * Get trustDocumentType
   * @return trustDocumentType
   */
  @javax.annotation.Nullable
  public TrustDocumentTypeEnum getTrustDocumentType() {
    return trustDocumentType;
  }

  public void setTrustDocumentType(TrustDocumentTypeEnum trustDocumentType) {
    this.trustDocumentType = trustDocumentType;
  }


  public SignedDocumentCreateDto correlationId(String correlationId) {
    this.correlationId = correlationId;
    return this;
  }

  /**
   * Get correlationId
   * @return correlationId
   */
  @javax.annotation.Nullable
  public String getCorrelationId() {
    return correlationId;
  }

  public void setCorrelationId(String correlationId) {
    this.correlationId = correlationId;
  }


  public SignedDocumentCreateDto externalReference(String externalReference) {
    this.externalReference = externalReference;
    return this;
  }

  /**
   * Get externalReference
   * @return externalReference
   */
  @javax.annotation.Nullable
  public String getExternalReference() {
    return externalReference;
  }

  public void setExternalReference(String externalReference) {
    this.externalReference = externalReference;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignedDocumentCreateDto signedDocumentCreateDto = (SignedDocumentCreateDto) o;
    return Objects.equals(this.id, signedDocumentCreateDto.id) &&
        Objects.equals(this.timestamp, signedDocumentCreateDto.timestamp) &&
        Objects.equals(this.url, signedDocumentCreateDto.url) &&
        Objects.equals(this.type, signedDocumentCreateDto.type) &&
        Objects.equals(this.title, signedDocumentCreateDto.title) &&
        Objects.equals(this.contentType, signedDocumentCreateDto.contentType) &&
        Objects.equals(this.contactId, signedDocumentCreateDto.contactId) &&
        Objects.equals(this.documentStandard, signedDocumentCreateDto.documentStandard) &&
        Objects.equals(this.trustDocumentType, signedDocumentCreateDto.trustDocumentType) &&
        Objects.equals(this.correlationId, signedDocumentCreateDto.correlationId) &&
        Objects.equals(this.externalReference, signedDocumentCreateDto.externalReference);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, timestamp, url, type, title, contentType, contactId, documentStandard, trustDocumentType, correlationId, externalReference);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignedDocumentCreateDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
    sb.append("    documentStandard: ").append(toIndentedString(documentStandard)).append("\n");
    sb.append("    trustDocumentType: ").append(toIndentedString(trustDocumentType)).append("\n");
    sb.append("    correlationId: ").append(toIndentedString(correlationId)).append("\n");
    sb.append("    externalReference: ").append(toIndentedString(externalReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("timestamp");
    openapiFields.add("url");
    openapiFields.add("type");
    openapiFields.add("title");
    openapiFields.add("contentType");
    openapiFields.add("contactId");
    openapiFields.add("documentStandard");
    openapiFields.add("trustDocumentType");
    openapiFields.add("correlationId");
    openapiFields.add("externalReference");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("title");
    openapiRequiredFields.add("contactId");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SignedDocumentCreateDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SignedDocumentCreateDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SignedDocumentCreateDto is not found in the empty JSON string", SignedDocumentCreateDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SignedDocumentCreateDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SignedDocumentCreateDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SignedDocumentCreateDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if (!jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("contentType") != null && !jsonObj.get("contentType").isJsonNull()) && !jsonObj.get("contentType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contentType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contentType").toString()));
      }
      if (!jsonObj.get("contactId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contactId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contactId").toString()));
      }
      if ((jsonObj.get("documentStandard") != null && !jsonObj.get("documentStandard").isJsonNull()) && !jsonObj.get("documentStandard").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `documentStandard` to be a primitive type in the JSON string but got `%s`", jsonObj.get("documentStandard").toString()));
      }
      // validate the optional field `documentStandard`
      if (jsonObj.get("documentStandard") != null && !jsonObj.get("documentStandard").isJsonNull()) {
        DocumentStandardEnum.validateJsonElement(jsonObj.get("documentStandard"));
      }
      if ((jsonObj.get("trustDocumentType") != null && !jsonObj.get("trustDocumentType").isJsonNull()) && !jsonObj.get("trustDocumentType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `trustDocumentType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("trustDocumentType").toString()));
      }
      // validate the optional field `trustDocumentType`
      if (jsonObj.get("trustDocumentType") != null && !jsonObj.get("trustDocumentType").isJsonNull()) {
        TrustDocumentTypeEnum.validateJsonElement(jsonObj.get("trustDocumentType"));
      }
      if ((jsonObj.get("correlationId") != null && !jsonObj.get("correlationId").isJsonNull()) && !jsonObj.get("correlationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `correlationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("correlationId").toString()));
      }
      if ((jsonObj.get("externalReference") != null && !jsonObj.get("externalReference").isJsonNull()) && !jsonObj.get("externalReference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `externalReference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("externalReference").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SignedDocumentCreateDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SignedDocumentCreateDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SignedDocumentCreateDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SignedDocumentCreateDto.class));

       return (TypeAdapter<T>) new TypeAdapter<SignedDocumentCreateDto>() {
           @Override
           public void write(JsonWriter out, SignedDocumentCreateDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SignedDocumentCreateDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SignedDocumentCreateDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SignedDocumentCreateDto
   * @throws IOException if the JSON string is invalid with respect to SignedDocumentCreateDto
   */
  public static SignedDocumentCreateDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SignedDocumentCreateDto.class);
  }

  /**
   * Convert an instance of SignedDocumentCreateDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

