openapi: 3.0.4
info:
  contact:
    email: support@fenix-alliance.com
    name: Fenix Alliance Inc.
    url: https://fenixalliance.com.co/Support
  license:
    name: Fenix Alliance Inc.
    url: https://fenix-alliance.com.co/Legal/Policies/eula
  termsOfService: https://absuite.net/eula
  title: EmailTemplates
  version: 2.0.0.0
servers:
- url: /
tags:
- name: FenixAlliance.ABP.Web
paths:
  /version:
    get:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABP.Web
      x-accepts:
      - application/json
  /health:
    get:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABP.Web
      x-accepts:
      - application/json
  /hello:
    get:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABP.Web
      x-accepts:
      - application/json
  /register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/problem+json
  /login:
    post:
      parameters:
      - explode: true
        in: query
        name: useCookies
        required: false
        schema:
          type: boolean
        style: form
      - explode: true
        in: query
        name: useSessionCookies
        required: false
        schema:
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
          description: OK
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/json
  /refresh:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
          description: OK
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/json
  /confirmEmail:
    get:
      operationId: MapIdentityApi-/confirmEmail
      parameters:
      - explode: true
        in: query
        name: userId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: code
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: changedEmail
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABP.Web
      x-accepts:
      - application/json
  /resendConfirmationEmail:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendConfirmationEmailRequest'
        required: true
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/json
  /forgotPassword:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/problem+json
  /resetPassword:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/problem+json
  /manage/2fa:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TwoFactorRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TwoFactorResponse'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/problem+json
  /manage/info:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - FenixAlliance.ABP.Web
      x-accepts:
      - application/json
      - application/problem+json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InfoRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/problem+json
components:
  schemas:
    AccessTokenResponse:
      additionalProperties: false
      example:
        expiresIn: 0
        tokenType: tokenType
        accessToken: accessToken
        refreshToken: refreshToken
      properties:
        tokenType:
          nullable: true
          readOnly: true
          type: string
        accessToken:
          nullable: true
          type: string
        expiresIn:
          format: int64
          type: integer
        refreshToken:
          nullable: true
          type: string
      required:
      - accessToken
      - expiresIn
      - refreshToken
      type: object
    ForgotPasswordRequest:
      additionalProperties: false
      example:
        email: email
      properties:
        email:
          nullable: true
          type: string
      required:
      - email
      type: object
    HttpValidationProblemDetails:
      additionalProperties: {}
      properties:
        type:
          nullable: true
          type: string
        title:
          nullable: true
          type: string
        status:
          format: int32
          nullable: true
          type: integer
        detail:
          nullable: true
          type: string
        instance:
          nullable: true
          type: string
        errors:
          additionalProperties:
            items:
              type: string
            type: array
          nullable: true
          type: object
      type: object
    InfoRequest:
      additionalProperties: false
      example:
        oldPassword: oldPassword
        newPassword: newPassword
        newEmail: newEmail
      properties:
        newEmail:
          nullable: true
          type: string
        newPassword:
          nullable: true
          type: string
        oldPassword:
          nullable: true
          type: string
      type: object
    InfoResponse:
      additionalProperties: false
      example:
        email: email
        isEmailConfirmed: true
      properties:
        email:
          nullable: true
          type: string
        isEmailConfirmed:
          type: boolean
      required:
      - email
      - isEmailConfirmed
      type: object
    LoginRequest:
      additionalProperties: false
      example:
        password: password
        twoFactorRecoveryCode: twoFactorRecoveryCode
        email: email
        twoFactorCode: twoFactorCode
      properties:
        email:
          nullable: true
          type: string
        password:
          nullable: true
          type: string
        twoFactorCode:
          nullable: true
          type: string
        twoFactorRecoveryCode:
          nullable: true
          type: string
      required:
      - email
      - password
      type: object
    RefreshRequest:
      additionalProperties: false
      example:
        refreshToken: refreshToken
      properties:
        refreshToken:
          nullable: true
          type: string
      required:
      - refreshToken
      type: object
    RegisterRequest:
      additionalProperties: false
      example:
        password: password
        email: email
      properties:
        email:
          nullable: true
          type: string
        password:
          nullable: true
          type: string
      required:
      - email
      - password
      type: object
    ResendConfirmationEmailRequest:
      additionalProperties: false
      example:
        email: email
      properties:
        email:
          nullable: true
          type: string
      required:
      - email
      type: object
    ResetPasswordRequest:
      additionalProperties: false
      example:
        resetCode: resetCode
        newPassword: newPassword
        email: email
      properties:
        email:
          nullable: true
          type: string
        resetCode:
          nullable: true
          type: string
        newPassword:
          nullable: true
          type: string
      required:
      - email
      - newPassword
      - resetCode
      type: object
    TwoFactorRequest:
      additionalProperties: false
      example:
        resetRecoveryCodes: true
        enable: true
        resetSharedKey: true
        forgetMachine: true
        twoFactorCode: twoFactorCode
      properties:
        enable:
          nullable: true
          type: boolean
        twoFactorCode:
          nullable: true
          type: string
        resetSharedKey:
          type: boolean
        resetRecoveryCodes:
          type: boolean
        forgetMachine:
          type: boolean
      type: object
    TwoFactorResponse:
      additionalProperties: false
      example:
        sharedKey: sharedKey
        isTwoFactorEnabled: true
        isMachineRemembered: true
        recoveryCodesLeft: 0
        recoveryCodes:
        - recoveryCodes
        - recoveryCodes
      properties:
        sharedKey:
          nullable: true
          type: string
        recoveryCodesLeft:
          format: int32
          type: integer
        recoveryCodes:
          items:
            type: string
          nullable: true
          type: array
        isTwoFactorEnabled:
          type: boolean
        isMachineRemembered:
          type: boolean
      required:
      - isMachineRemembered
      - isTwoFactorEnabled
      - recoveryCodesLeft
      - sharedKey
      type: object

